"""Feature 216 — ``mechanism_discrimination``, persisted per candidate model.

*"System persists mechanism_discrimination per candidate model before the gate
milestone, so a weak agent is not misread as a failed thesis."*

docs/nullius-tech-architecture.md §14.1 states the instrument feature 214
persists per campaign, and the sentence that makes the *per-model* half a
requirement rather than a refinement (§14.1)::

    **Run this at M2, before the M3 gate.**  Two campaigns per candidate model,
    roughly $60.  Skip it and a weak signal agent will present as a failed
    thesis, and you will disprove the wrong hypothesis.

and §14.1's mitigation 3 says what the stratified form is for::

    **Record and stratify.**  ``agent_model_id`` is indexed for exactly this;
    report M3 results per model stratum as well as pooled.

docs/alpha-engine-prd.md §13 invariant 5a states the same as an invariant::

    Every node records ``agent_model_id``.  Provider aliases re-route silently;
    a pinned snapshot or a self-hosted checkpoint hash is the only real
    guarantee.  **M3 results are reported per model stratum as well as pooled.**

**The risk row is the sentence's purpose clause, verbatim.**  PRD §14::

    | Signal agent too weak, read as a failed thesis | High | Measure
    | ``mechanism_discrimination`` at M2, before the gate (arch §14.1) |

so the feature is the *stratification* that row's detection depends on: a pooled
figure over a mixed pool attributes a weak agent's collapsed correlation to the
campaign, and the campaign's failure is then read as the thesis's.

**What this module is, in one line.**  Feature 214 persists the figure **per
campaign**; this persists the same figure **per candidate model**, into a table
this member owns, keyed by the ``(campaign, model)`` pair — §14.1's *"two
campaigns per candidate model"* being the reason the campaign stays in the key.

**What this module is not.**

* It is not feature 214, and 214 is edited nowhere.  That feature's row is the
  *pooled* (well — the campaign-scoped) reading and stays exactly as its own
  suite pins it; this feature cannot produce that row, and 214 cannot produce
  this one.
* It is not feature 215's count, although 215 is the nearest neighbour in one
  respect worth stating so a reader does not confuse the two: 215 *derives* its
  per-model strata by grouping a campaign's whole proposal history, and returns a
  mapping with no row behind it.  Here the model is a **declared and verified**
  input and the figure is **written down** — see "the stratum is verified, never
  derived".
* It is not a gate, a milestone or a verdict.  No milestone is a *value* in this
  workspace (§14.1's M2/M3 appear in code only as citations, and feature 187's
  ``bootstrap._claim`` takes the gate's world count as a caller-supplied keyword
  precisely because the gate is not a stored state), so "before the gate
  milestone" is discharged the only way it can be — as a *structural* claim about
  what this module reads; see :data:`GATE_SQL_TABLES` and the suite case that
  pins it.
* It is not a pooled figure, and cannot be asked for one: there is no default
  model and no "all models" read.  See "there is no default, and no pooled
  answer".

**The stratum is verified, never derived.**  A cohort is the one thing this
member may not assemble after the fact (§14.1 rule 1, argued at 214's
``_validated_cohort``), and at M2 a campaign *is* a candidate model's unit — so
the tempting implementation is to group the declared cohort by
``node.agent_model_id`` and write one row per bucket.  Refused, for a reason that
is the whole point of the sentence: §14.1 records the provenance failure as
*"not hypothetical"* — DeepSeek retired ``deepseek-v4-flash`` in September 2026
while continuing to accept the ID, so two campaigns under one model string were
generated by **different models**.  A deriving implementation would take that
mixed pool and report two tidy small-``n`` strata, which is exactly the flattering
shape; a *declaring* implementation refuses it by name and sends the operator to
:class:`CandidateModelError`.  What §14.1's mitigation 3 asks of a *derivation*
is the M3 paired comparison — a different feature over a different table — while
the M2 instrument is asked to **measure a candidate model**, and a figure
attributed to a model that did not author every branch in it is the misreading
this feature exists to prevent.

**There is no default, and no pooled answer.**  A missing, blank or non-string
model is refused, and the signature has no shape that omits one.  The failure the
sentence names — *"a weak agent is not misread as a failed thesis"* — is a
*failure of pooling*, so a default would restore it by omission.  That is 214's
argument for refusing a default cohort (*"a caller that could just correlate
everything would get a number that silently mixes the exactly-zero half"*) made
one level up: here the thing a default would silently mix is a second agent.  The
pooled figure is not lost — it is 214's, one call away, in
``campaign_discrimination``; what this feature declines is producing it *instead
of* the stratified one.

**One thing this module restates, and one thing it does not.**  It **does not**
restate the arithmetic.  A second ``_pearson`` here would be a second definition
of §14.1's statistic and a second definition of the Fisher-z interval its rule 3
requires, so this module imports both from :mod:`signal_agent._discrimination`,
together with the two half-reads, the two store-shape checks and 214's own
:class:`~signal_agent.MechanismDiscrimination` — the precedent for reaching a
sibling inside the member being feature 213's ``_themes._SLUG_RE``, reached
*"through :mod:`signal_agent._themes` rather than re-spelled"*.  It **does**
restate every name it reads (``node_proposal``, ``node``, ``agent_model_id``,
``replay_score``, ``campaign``), for the reason every store in this workspace
restates its own — and the member's own suite asserts the two spellings agree
rather than leaving them to drift.

**What "the halves" means here.**  The in-sample half is 214's
:data:`~signal_agent.IS_GAIN_METRIC` — ``ir_marginal``, read from the snapshot
207 froze beside each proposal rather than from ``node``'s live column, because
feature 240 refreshes that row in place.  The out-of-sample half is the mean of
the ``replay_score`` rows whose ``committed_pick`` is the branch.  A branch is
**one point** at the mean of its runs, because §14.1's unit is the branch.  Both
are read by 214's functions, so the two figures over one cohort cannot disagree
about what a branch's gain is.

**The frozen cohort, and why this digest differs from 214's.**  §14.1 rule 1:
*"Freeze the cohort before any model runs, and hash its inputs."*  The model is
an input to a model-scoped figure, so :func:`_cohort_digest` hashes it in the
header lines beside the campaign, the revision and the metric.  Measuring one
campaign's one model with both features over the *same* branch list therefore
yields two **different** digests — and that is the honest reading rather than a
defect: the two rows are two different readings, and a colliding digest would
claim they were the same inputs.  What 214's plan sentence asks for is the
*mechanism* — *"so 216's stratified reading can be shown to be over the same
inputs"* — and this row is auditable exactly the way that row is: a report
publishes the figure and the hash of the branches and gains behind it.

**Why no component, and why no seat.**  The reading resolves no configuration of
its own: the tables, the column, the metric pair and the figure's shape are all
facts about state two existing component builders already expose (207's store and
the tree it lives in).  So it is a free function beside them, reached as
``from signal_agent import mechanism_discrimination_by_model``, exactly as feature
186's :func:`bootstrap.world_census` sits beside the bootstrap pool, 215's
``tree_diversity`` sits beside the history store and 214's
``mechanism_discrimination`` sits beside this one.  A tenth ``signal-agent-*``
registration would put a name in the registry for a question that composes
nothing, and this feature has no *composed component* to read.

Stdlib only (plus this member's own modules), and import-cheap: no third-party
import at module scope, so the factory's scan — which imports this member to fire
its ``@register`` builders — pays nothing for this module.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from collections.abc import Mapping
from contextlib import closing
from datetime import datetime
from pathlib import Path
from types import MappingProxyType
from typing import Any, Final

from ._discrimination import (
    CAMPAIGN_ID_COLUMN,
    CAMPAIGN_TABLE,
    CONFIDENCE_LEVEL,
    DISCRIMINATION_TABLE,
    IS_GAIN_METRIC,
    MINIMUM_PAIRS,
    REPLAY_SCORE_TABLE,
    MechanismDiscrimination,
    _interval,
    _pearson,
    _proposal_history,
    _read_is_half,
    _read_oos_half,
    _require_campaign,
    _require_correlation,
    _require_spread,
    _require_tables,
    _utc_now,
    _validated_campaign_id,
    _validated_cohort,
)
from .errors import (
    CandidateModelError,
    DiscriminationCohortError,
)

__all__ = [
    "CANDIDATE_TABLE",
    "MODEL_METRIC",
    "ModelDiscrimination",
    "load_model_discrimination",
    "load_model_discriminations",
    "mechanism_discrimination_by_model",
]

#: This member's second owned table — the row feature 216's sentence persists.
#: Created lazily by :func:`mechanism_discrimination_by_model` and declared
#: nowhere in the shared migration chain, the precedent ``bootstrap_world``
#: (feature 188), ``depth_run_window`` (202), ``bootstrap_trial`` (185),
#: ``depth_cache_rate`` (200), ``node_proposal`` (207), ``campaign_ks_guard``
#: (123) and 214's own :data:`~signal_agent.DISCRIMINATION_TABLE` all set.
#:
#: **Why not a column on 214's table, and not on ``campaign``.**  ``campaign``
#: (``0111``) carries ``calibration_status`` and ``ks_pvalue`` and no
#: discrimination column, and ``migrations/versions/**`` is a shared,
#: order-sensitive tree this feature must not edit.  214's table is out for a
#: sharper reason: its primary key is the campaign, so a per-model row would
#: either collide with the campaign's own row or force a nullable model column
#: on a table whose grain would then be two things at once.  The two features
#: measure the same statistic over different *units*, so they get two tables —
#: which is also what lets each one's `load` answer without the other's rows
#: being in the way.
#:
#: Named for what it holds rather than for the figure: one row is one
#: *candidate model's* reading of one campaign, and the name says so before the
#: columns do.
CANDIDATE_TABLE: Final[str] = "campaign_model_discrimination"

#: The metric this feature's figure is grouped and reported under, spelled
#: beside :data:`~signal_agent.IS_GAIN_METRIC` rather than re-derived from it,
#: because the two answer different questions: that constant is *which column
#: the in-sample half is read from*, and this one is *which figure the row
#: holds*.  They are the same string today and the member's suite pins that they
#: agree; a name that said only ``ir_marginal`` would leave a reader unable to
#: tell whether a row was a metric or a reading of one.
MODEL_METRIC: Final[str] = "mechanism_discrimination"

#: ``0115``'s column on ``node`` — the stratum, and the whole subject of the
#: feature.  Spelled here as a literal rather than imported from
#: :mod:`signal_agent._diversity`, for the reason every store in this workspace
#: restates its own: a private constant of a sibling module is not a promise.
#: The name is ``signal_agent.MODEL_COLUMN``'s — and 215's, which is where the
#: member first joined it — and the member's own suite asserts the two spellings
#: agree rather than leaving them to drift.
MODEL_COLUMN: Final[str] = "agent_model_id"

#: ``0118``'s table, probed and never created: it is the discovery tree's.  A
#: *third* module in this member now names it, and it is spelled again rather
#: than imported for 207's and 215's reason, word for word.
NODE_TABLE: Final[str] = "node"

#: ``0118``'s primary key.
NODE_ID_COLUMN: Final[str] = "id"

#: Feature 207's member-owned table, and its key — deliberately two constants
#: and not one, for the reason :data:`signal_agent._diversity.NODE_ID_COLUMN`
#: gives at length: the join is ``node.id = node_proposal.node_id``, and one
#: constant spelled in both places is how a join comes to be written ``n.id =
#: p.id``, which SQLite answers with *no such column*.
NODE_PROPOSAL_TABLE: Final[str] = "node_proposal"
NODE_PROPOSAL_NODE_COLUMN: Final[str] = "node_id"

#: The revision that adds :data:`MODEL_COLUMN` — feature 100's migration, the
#: whole actionable content of a :class:`CandidateModelError` raised for a tree
#: that has not reached it.
MODEL_POLICY_REVISION: Final[str] = "0115_agent_model_trio"

#: The revision that creates :data:`NODE_TABLE` — feature 97's.
NODE_POLICY_REVISION: Final[str] = "0118_node_table"

#: The ``sqlite_master`` probe, read-only, asked before anything else.
_TABLE_EXISTS_SQL: Final[str] = (
    "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?"
)

#: The read that answers *which columns does the tree actually have?* — the
#: ``PRAGMA`` probe 215's ``_tree_columns`` makes for the same column, for the
#: reason it gives: SQLite answers *"no such column"* only once a statement
#: mentions it, which reports the gap as a fact about a statement rather than
#: about the deployment.
_TREE_COLUMNS_SQL: Final[str] = f"PRAGMA table_info({NODE_TABLE})"

#: **The attribution walk** — the statement that makes the feature's subject
#: verifiable, and the one statement in this module that is not one of 214's.
#:
#: One ``IN`` over the declared cohort, so a single read answers for every
#: branch — the same reason 214's ``_IS_HALF_SQL`` uses one, and the same
#: consequence: because the placeholders are the *caller's* cohort, a branch the
#: caller did not declare is never read at all, so the ``| real branches``
#: qualifier is built into what the statement can return rather than applied to
#: its output.
#:
#: It **reads the model and nothing else**.  ``stated_mechanism`` is not selected
#: — feature 211's barrier, which 215 argues at length from its own side, and
#: which bites here for the same reason: this feature's sentence *is* the
#: ``agent_model_id`` stratification the barrier's refusal names in as many
#: words.  A column that is not selected cannot reach the figure.
_ATTRIBUTION_SQL: Final[str] = (
    f"SELECT {NODE_ID_COLUMN}, {MODEL_COLUMN} FROM {NODE_TABLE} "
    f"WHERE {NODE_ID_COLUMN} IN ({{placeholders}})"
)

#: The cohort size one campaign recorded for one model — *how many proposals this
#: model wrote here*.  It is §14.1's denominator for the stratum, and it is the
#: figure a bare correlation cannot be read without: *"r = 0.31"* over four
#: branches and the same figure over forty are different claims, and §14.1's rule
#: 2 — *"both trivial baselines appear in every table"* — is the same argument
#: from the other end.
#:
#: Counted over ``node_proposal`` joined to ``node`` and filtered by the model,
#: so it is *this model's* share of the campaign and not the campaign's size —
#: the distinction 215's own denominator deliberately does not make, because 215
#: returns the per-model figures and the pooled denominator together and this
#: feature returns one stratum.
_MODEL_PROPOSALS_SQL: Final[str] = f"""
SELECT COUNT(*) FROM {NODE_PROPOSAL_TABLE} AS p
JOIN {NODE_TABLE} AS n ON n.{NODE_ID_COLUMN} = p.{NODE_PROPOSAL_NODE_COLUMN}
WHERE p.{CAMPAIGN_ID_COLUMN} = ?
  AND n.{MODEL_COLUMN} = ?
"""

#: This feature's row: one per ``(campaign, model)`` pair, holding the figure and
#: its interval, the two denominators, the revision the runs were under, the
#: digest of the frozen cohort, the stratum's own proposal count, and when the
#: reading was taken.
#:
#: **The primary key is the pair, and that is §14.1's grain rather than a
#: composite slapped on.**  §14.1 budgets *"two campaigns per candidate model"*,
#: so a candidate model's M2 evidence **is** two rows and a table keyed on the
#: model alone could hold only the second.  A re-reading of one pair refreshes
#: rather than appends — feature 123's grain for a campaign-scoped statistic,
#: 214's for the same reason: the instrument is run at M2 over a cohort that
#: grows as the campaign proposes, so a pair is expected to be measured more than
#: once and what the table must hold is the latest reading and nothing else.
#:
#: **Both key columns are ``NOT NULL`` beside ``PRIMARY KEY``** for the reason
#: ``0111``'s docstring spells and 214's schema quotes: SQLite accepts ``NULL`` —
#: and several — in a rowid table's bare ``PRIMARY KEY``, so a second
#: NULL-keyed row would split a reading from its identity while still being
#: accepted as a distinct key.
#:
#: **The interval is two columns and not a derived read**, for 214's reason word
#: for word: §14.1 rule 3 makes the interval the *reported* thing (``design.md``
#: §9), so a row holding the point alone would let a report print it
#: unaccompanied, which is the failure the rule exists to prevent.
#:
#: **``proposals`` is the stratum's denominator, not the cohort's.**  ``pairs``
#: is how many branches the figure is over; ``proposals`` is how many documents
#: this model wrote in this campaign.  They are different numbers and the gap
#: between them is a fact a report needs — a model that wrote forty proposals
#: and had four of them declared real is a different reading from one that wrote
#: four — which is why both are stored rather than one being derived from the
#: other.  No ``CHECK`` constraints: validation lives in the value object and in
#: the read path's *reconstruction*, which is 214's answer to the defence feature
#: 123 gets from writing its figure onto two rows.
_SCHEMA: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {CANDIDATE_TABLE} (
    campaign_id    TEXT     NOT NULL,
    model          TEXT     NOT NULL,
    correlation    REAL     NOT NULL,
    interval_lower REAL     NOT NULL,
    interval_upper REAL     NOT NULL,
    pairs          INT      NOT NULL,
    runs           INT      NOT NULL,
    proposals      INT      NOT NULL,
    policy_version TEXT     NOT NULL,
    cohort_digest  CHAR(64) NOT NULL,
    seen_at        TEXT     NOT NULL,
    PRIMARY KEY (campaign_id, model)
)
"""

#: The stored row's columns, in the order the schema declares them.  One tuple so
#: the write and the read cannot drift apart on what this feature's row is made
#: of — 214's own discipline, applied to a wider row.
_COLUMNS: Final[tuple[str, ...]] = (
    "campaign_id",
    "model",
    "correlation",
    "interval_lower",
    "interval_upper",
    "pairs",
    "runs",
    "proposals",
    "policy_version",
    "cohort_digest",
    "seen_at",
)

#: **The tables this module may name, and the claim that makes it "before the
#: gate".**  No milestone, gate verdict or gate arithmetic is a *value* anywhere
#: in this workspace: ``M2``/``M3`` appear in code only as citations of the
#: architecture, and feature 187's ``bootstrap._claim`` takes the gate's world
#: count as a caller-supplied keyword precisely because the gate itself is not a
#: stored state.  So "before the gate milestone" is discharged the only way it
#: can be — **structurally**: the instrument must be computable from what exists
#: before the gate, and must read nothing the gate produces.  Every table named
#: above is a pre-M3 table: feature 207's proposals, feature 97's tree and
#: feature 100's model column, ``0109``'s replay pool and ``0111``'s campaign —
#: plus this feature's own row.  The member's own suite pins that over the
#: module's source: no ``*_SQL`` constant and no code token names a table outside
#: this set, and no gate token appears at all.
#:
#: (For the same reason there is no ``_GATE_SQL_FORBIDDEN`` tuple to point at: a
#: constant listing the tokens this module must not name would itself name them.
#: The forbidden vocabulary lives in the suite, where naming it is the claim.)
GATE_SQL_TABLES: Final[tuple[str, ...]] = (
    CAMPAIGN_TABLE,
    CANDIDATE_TABLE,
    DISCRIMINATION_TABLE,
    NODE_TABLE,
    NODE_PROPOSAL_TABLE,
    REPLAY_SCORE_TABLE,
)


# ── The stratum ──────────────────────────────────────────────────────────────


def _validated_model(value: Any) -> str:
    """Validate the candidate model: a non-blank string, and not a flag.

    The floor of the feature, and the argument for it is decision 2 above: the
    failure the sentence names is a *pooled* reading, so there is no default here
    to fall back to and no way to ask for "the figure" without naming who it is
    about.  ``bool`` is refused explicitly because ``True`` is ``1`` in Python —
    the trap 214's ``_validated_count`` and 215's ``_validated_model`` each name
    for their own arguments.

    The value is returned **verbatim, stripped of nothing**.  203's
    :func:`providers.require_agent_model_id` owns what a model id may be, and
    this module only refuses the ones that name no model at all rather than
    reshaping one that does — 215's rule for the same column, and the reason a
    dropped trailing space here would silently merge two strata.
    """
    if isinstance(value, bool) or not isinstance(value, str) or not value.strip():
        raise CandidateModelError(
            f"the candidate model is {value!r} ({type(value).__name__}) rather "
            f"than a non-empty model id: feature 216's sentence is *persists "
            f"mechanism_discrimination per candidate model*, §14.1 budgets two "
            f"campaigns per candidate model, and a reading that names no model "
            f"cannot be printed as a stratum beside the real ones — which is the "
            f"pooled reading the sentence exists to prevent, and the reason this "
            f"argument has no default (feature 216)."
        )
    return value


def _validated_cohort_size(value: Any, *, name: str) -> int:
    """Validate one denominator: a whole number, not a flag, not negative."""
    if isinstance(value, bool) or not isinstance(value, int):
        raise CandidateModelError(
            f"a candidate-model reading's {name} is {value!r} "
            f"({type(value).__name__}) rather than a whole number: it is how "
            f"many {'branches the figure is over' if name == 'pairs' else 'proposals this model wrote'} "
            f"and a value that is not a count is a reading no measurement could "
            f"produce. ``bool`` is refused explicitly because ``True`` is ``1`` "
            f"in Python (feature 216)."
        )
    if value < 0:
        raise CandidateModelError(
            f"a candidate-model reading's {name} cannot be negative — got "
            f"{value!r}: a cohort holds zero branches or more (feature 216)."
        )
    return value


# ── The attribution ──────────────────────────────────────────────────────────


def _verify_attribution(
    connection: sqlite3.Connection,
    cohort: tuple[str, ...],
    model: str,
    campaign: str,
) -> dict[str, str]:
    """Read every declared branch's authoring model, or refuse by name.

    **This is the feature.**  Every other read here is 214's; this one is the
    per-model half of the sentence, and it is the half that is *verifiable*:
    ``agent_model_id`` is a column on a table this member may read (``0115``,
    indexed by ``0113`` for exactly this stratification), unlike the real/null
    discriminant which is absent from the store entirely.  So where 214 must hash
    its cohort and hope, this feature can check.

    Three refusals, each naming the branch and the model:

    * **the tree is not there.**  No ``node`` table is feature 97's revision and
      a ``node`` table without :data:`MODEL_COLUMN` is feature 100's — two
      depths and two refusals, kept apart because the repairs differ, the
      discipline 215's ``_tree_columns`` follows for the same column.  Both are
      :class:`CandidateModelError`, because both mean the same thing for *this*
      feature: the per-model half of its sentence cannot be answered at all, and
      no flat number is offered in its place.
    * **the branch's node is absent.**  A declared branch the tree does not hold
      has no authoring model and cannot be attributed.  Refused rather than
      dropped, for rule 1's reason: a figure computed over whatever subset
      happened to be attributable is a cohort assembled after the fact *by
      availability*.
    * **the branch is authored by another model.**  The whole point.  The stored
      value is the authority — it is what feature 100's migration wrote on the
      node at authoring time — and a mismatch is the provenance failure §14.1
      documents as *"not hypothetical"*, refused by name so the operator sees
      *which* branch and *which* two model strings disagree rather than two tidy
      small-``n`` strata.

    **The tree's columns are asked before the walk**, and that ordering is
    load-bearing rather than stylistic: the walk's SQL mentions
    :data:`MODEL_COLUMN`, so on a tree that has not reached ``0115`` it would
    fail as ``no such column`` — a fact about a statement, reported in SQLite's
    vocabulary instead of this member's.  Asking the shape first is what makes
    the refusal name the losing revision.
    """
    columns = _tree_columns(connection)
    assert MODEL_COLUMN in columns, "the column is required before the walk"
    placeholders = ", ".join("?" for _ in cohort)
    rows = connection.execute(
        _ATTRIBUTION_SQL.format(placeholders=placeholders), cohort
    ).fetchall()
    stored = {str(node): author for node, author in rows}
    authors: dict[str, str] = {}
    for branch in cohort:
        if branch not in stored:
            raise CandidateModelError(
                f"real branch {branch!r} belongs to no node in this tree, so "
                f"the candidate model that authored it cannot be established: "
                f"feature 216's figure is scoped to *one* candidate model, and "
                f"a branch the tree does not hold names no author. Refused "
                f"rather than dropped — a cohort reduced after the fact to "
                f"whatever happened to be attributable is a selection, not a "
                f"sample (§14.1 rule 1, feature 216)."
            )
        author = stored[branch]
        if author is None or not str(author).strip():
            raise CandidateModelError(
                f"real branch {branch!r} has a node with no {MODEL_COLUMN} in "
                f"this tree, so it cannot be attributed to a candidate model: "
                f"revision {MODEL_POLICY_REVISION} declares that column NOT NULL "
                f"because *every node is authored by exactly one model* (PRD §13 "
                f"invariant 5a), so a node without one is either a tree the "
                f"chain has not reached or a row a hand has been to. Feature "
                f"216's figure is *per candidate model*, and a branch whose "
                f"author is unknown would have to be attributed to one anyway "
                f"(feature 216)."
            )
        text = str(author)
        if text != model:
            raise CandidateModelError(
                f"real branch {branch!r} is declared as a member of candidate "
                f"model {model!r}, but its node records {text!r}: feature 216's "
                f"sentence is *persists mechanism_discrimination per candidate "
                f"model*, and §14.1 records the provenance failure this guard "
                f"exists for as *not hypothetical* — DeepSeek retired "
                f"`deepseek-v4-flash` on 2026-09-10 while continuing to accept "
                f"the ID and silently serving V4.1-Flash, so one string can span "
                f"two models. A figure correlated across both and attributed to "
                f"either would be the pooled reading §14.1 mitigation 3 and PRD "
                f"§13 5a stratify to avoid; declare the model that authored "
                f"these branches, or measure each stratum's branches separately "
                f"(feature 216)."
            )
        authors[branch] = text
    return authors


def _tree_columns(connection: sqlite3.Connection) -> frozenset[str]:
    """The live ``node`` table's columns, the missing table refused by name.

    One line of shared vocabulary and two refusals, and the two are kept apart
    because the repairs differ: no ``node`` table is feature 97's revision and a
    table without :data:`MODEL_COLUMN` is feature 100's.  Naming the losing
    revision is the whole actionable content — the discipline feature 215's
    ``_tree_columns`` follows for its own two depths, and
    :class:`~signal_agent.MechanismColumnError` for its own column.

    Refused as :class:`CandidateModelError` here, where 215 refuses the absent
    table as :class:`ProposalNodeNotRecordedError` (207's, reused): 215's figure
    needs the tree for its *stratum* but is fundamentally a count of proposals,
    so an absent tree is a history fact; this feature's subject **is** the model
    column, so both depths are one fact about *this* reading and share this
    feature's class.
    """
    rows = connection.execute(_TREE_COLUMNS_SQL).fetchall()
    columns = frozenset(str(row[1]) for row in rows)
    if not columns:
        raise CandidateModelError(
            f"the store at this path has no {NODE_TABLE} table, so there is no "
            f"tree to attribute a campaign's branches to: feature 216's figure "
            f"is scoped to one candidate model, the model is "
            f"{MODEL_COLUMN} on each node, and a node is feature 97's row — "
            f"revision {NODE_POLICY_REVISION}. Run the migration chain to "
            f"there, then record the campaign (feature 216)."
        )
    if MODEL_COLUMN not in columns:
        raise CandidateModelError(
            f"the {NODE_TABLE} table holds no {MODEL_COLUMN} column, so a "
            f"campaign's branches cannot be attributed *per candidate model*: "
            f"the column belongs to revision {MODEL_POLICY_REVISION} (feature "
            f"100), and feature 216's sentence is *persists "
            f"mechanism_discrimination per candidate model* — a tree that has "
            f"not reached it can answer no per-model figure at all, and "
            f"reporting the campaign's pooled number in its place would be the "
            f"very reading the sentence exists to prevent. Run the migration "
            f"chain to {MODEL_POLICY_REVISION} (feature 216)."
        )
    return columns


# ── The frozen cohort, §14.1's rule 1 ────────────────────────────────────────


def _cohort_digest(
    campaign: str,
    model: str,
    policy_version: str,
    pairs: tuple[tuple[str, float, float], ...],
) -> str:
    """Hash the inputs this figure was computed over — §14.1's rule 1.

    *"Freeze the cohort before any model runs, and hash its inputs."*  214's
    digest over the same triples with **one line added**: the candidate model.

    **Why the model is an input and not merely a column of the row.**  The
    digest's job is to make a published figure's inputs auditable — to answer
    *over what was this number computed*.  For a model-scoped reading, *which
    model* is the first answer to that question and not the last: the same
    campaign, the same revision, the same branches and the same two series of
    gains produce a *different claim* when attributed to
    ``deepseek/deepseek-v4-flash/2026-09-10`` than when attributed to
    ``anthropic/claude-opus-5-5/2026-09-01``.  A digest that omitted it would
    hash two different readings alike.

    **The consequence is stated rather than left to be discovered.**  Measuring
    one campaign's one model with both features over the *same* branch list
    yields two **different** digests.  That is the honest reading: the two rows
    are two different readings (one about a campaign, one about a model), and a
    colliding digest would claim they were the same inputs.  What 214's plan
    sentence asks of this feature — *"so 216's stratified reading can be shown
    to be over the same inputs"* — is satisfied by the *mechanism*: a report can
    show which branches and which gains produced this row, exactly as it can for
    that one.

    Order is imposed here rather than trusted (the pairs are sorted by branch id
    by the caller, which is what makes the digest a statement about the cohort's
    *contents* rather than about the caller's iteration order), and the floats
    are rendered with ``repr``, which round-trips a float exactly — both 214's
    decisions, applied unchanged.
    """
    lines = [
        campaign,
        model,
        policy_version,
        IS_GAIN_METRIC,
        f"{CONFIDENCE_LEVEL!r}",
    ]
    lines.extend(
        f"{branch}\t{is_gain!r}\t{oos_gain!r}"
        for branch, is_gain, oos_gain in pairs
    )
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()


# ── The value ────────────────────────────────────────────────────────────────


class ModelDiscrimination:
    """One candidate model's ``mechanism_discrimination`` on one campaign.

    The value :func:`mechanism_discrimination_by_model` persists and
    :func:`load_model_discrimination` reads back.  It is :class:`MechanismDiscrimination`
    with one more thing on it, and the relation between the two is deliberately
    *not* a subclass: 214's value is the **whole** of that feature's answer and
    its constructor refuses anything its own read could not produce, so deriving
    from it would mean either widening 214's validation with a field that is not
    its subject or building a second, half-validated thing.

    What this adds is the pair and the stratum's denominator:

    * :attr:`model` — the candidate model this figure is *about*, held beside
      the campaign rather than only in the table's key, because the whole point
      of the feature is that the figure reaches a report *attributed*.
    * :attr:`proposals` — how many documents this model wrote in this campaign.
      §14.1's rule 2 read as a structural requirement rather than a formatting
      one: *"both trivial baselines appear in every table"*, and the figure a
      correlation must be read against is the *denominator* it was drawn from.
      ``pairs`` is how many branches the figure is over; this is how many the
      model wrote.  They are different numbers and the gap between them is a
      fact a report needs — forty proposals with four declared real is a
      different reading from four proposals with four declared real — which is
      why it is a field and not a derived sum.

    **Everything else is 214's, and delegated to it rather than re-validated.**
    A compositional :class:`MechanismDiscrimination` is built inside
    :meth:`__init__`, so the floor, the interval's self-consistency, the
    ``runs >= pairs`` relation, the digest's shape and the stamp's tz-awareness
    are checked by the constructor that already owns those checks.  Re-spelling
    them here would be a second definition of 214's invariants, which is the
    duplication this feature's module docstring refuses for the arithmetic and
    refuses here for the same reason.

    **Immutable, and validated at construction rather than trusted** — 214's
    discipline, for its reason: every field here reaches a report that a weak
    agent's verdict is read off, so a value no read could produce is refused
    rather than printed.
    """

    __slots__ = ("_model", "_proposals", "_reading")

    def __init__(
        self,
        *,
        campaign_id: str,
        model: str,
        correlation: float,
        lower: float,
        upper: float,
        pairs: int,
        runs: int,
        proposals: int,
        policy_version: str,
        cohort_digest: str,
        seen_at: datetime,
    ) -> None:
        self._model = _validated_model(model)
        counted = _validated_cohort_size(proposals, name="proposals")
        self._reading = MechanismDiscrimination(
            campaign_id=campaign_id,
            correlation=correlation,
            lower=lower,
            upper=upper,
            pairs=pairs,
            runs=runs,
            policy_version=policy_version,
            cohort_digest=cohort_digest,
            seen_at=seen_at,
        )
        self._proposals = counted

    @property
    def model(self) -> str:
        """The candidate model this reading is *about*, verbatim as recorded.

        Held as the column holds it rather than normalised, for 215's reason: the
        stratum this figure is attributed to has to be the stratum the M3 paired
        comparison groups by (PRD §13 5a), and 203's
        :func:`providers.require_agent_model_id` owns what a model id may be.
        """
        return self._model

    @property
    def campaign_id(self) -> str:
        """The campaign this reading is scoped to, in canonical UUID text."""
        return self._reading.campaign_id

    @property
    def correlation(self) -> float:
        """The point estimate — the hairline inside the interval, not the mark."""
        return self._reading.correlation

    @property
    def lower(self) -> float:
        """The lower bound of the 95% interval."""
        return self._reading.lower

    @property
    def upper(self) -> float:
        """The upper bound of the 95% interval."""
        return self._reading.upper

    @property
    def interval(self) -> tuple[float, float]:
        """The two bounds as one pair — the primary mark, in one value."""
        return self._reading.interval

    @property
    def pairs(self) -> int:
        """How many real branches the figure is over — the interval's ``n``."""
        return self._reading.pairs

    @property
    def runs(self) -> int:
        """How many ``replay_score`` rows were drawn on."""
        return self._reading.runs

    @property
    def proposals(self) -> int:
        """How many proposals this candidate model wrote in this campaign.

        §14.1's denominator for the stratum, and not the same number as
        :attr:`pairs` — see the class docstring.
        """
        return self._proposals

    @property
    def policy_version(self) -> str:
        """The single policy revision every run in the cohort was under."""
        return self._reading.policy_version

    @property
    def cohort_digest(self) -> str:
        """The sha256 over the frozen cohort's inputs, the model among them."""
        return self._reading.cohort_digest

    @property
    def seen_at(self) -> datetime:
        """When the reading was taken."""
        return self._reading.seen_at

    def reading(self) -> MechanismDiscrimination:
        """The campaign-scoped reading this one is built on.

        Exposed because it is not a copy: it is 214's own value, validated by
        214's own constructor, and a report that wants the campaign-scoped
        shape — :meth:`MechanismDiscrimination.row`, its ``payload``, its
        arithmetic against one bound — should get *that object* rather than a
        second, parallel spelling of it here.  The one field it does not carry
        is the model, because 214's value has no such field and will not grow
        one: this feature's row is where the attribution lives.

        The returned object is immutable, so handing it out costs nothing.
        """
        return self._reading

    def row(self) -> dict[str, Any]:
        """The reading as a report-shaped mapping — a fresh dict per call.

        The shape feature 186's :meth:`WorldCensus.row`, 215's
        :meth:`TreeDiversity.row`, 123's ``to_payload`` and 214's own ``row``
        return: a new mapping each time, so a report tool that writes into what
        it read moves its own copy.

        **``interval`` is nested and ``model`` is beside ``campaign_id``**, and
        both are §14.1's reporting rules in the shape of the data.  The nesting
        is 214's (``design.md`` §9: the interval is the primary mark and the
        point a hairline within it, so a flat row invites a renderer to print
        the point alone).  The placing of ``model`` is this feature's: §14.1
        mitigation 3 and PRD §13 5a report *per model stratum*, so the stratum is
        a top-level key of the row rather than a column of the table — a report
        that did not carry it could not be tabulated per model, which is the
        whole of what the sentence asks for.  ``seen_at`` is rendered as
        ISO-8601 text, the form the column holds.
        """
        return {
            "campaign_id": self._reading.campaign_id,
            "model": self._model,
            "interval": {"lower": self._reading.lower, "upper": self._reading.upper},
            "correlation": self._reading.correlation,
            "pairs": self._reading.pairs,
            "runs": self._reading.runs,
            "proposals": self._proposals,
            "policy_version": self._reading.policy_version,
            "cohort_digest": self._reading.cohort_digest,
            "seen_at": self._reading.seen_at.isoformat(),
        }

    def payload(self) -> str:
        """The reading as one sorted JSON line — the shape a report stores."""
        return json.dumps(self.row(), sort_keys=True, separators=(",", ":"))

    def __eq__(self, other: object) -> bool:
        """Equal when the parts are equal — never by ``isinstance``.

        The loader imports every member twice, once by file path under a
        synthetic name and once as the importable member, so an ``isinstance``
        check would be false for a value built from the other import of the same
        file.  Equality over the fields is the same statement and survives that
        — 214's and 215's decision, applied here.
        """
        if not isinstance(other, ModelDiscrimination):
            return NotImplemented
        return (
            self._model == other._model
            and self._proposals == other._proposals
            and self._reading == other._reading
        )

    def __hash__(self) -> int:
        return hash((self._model, self._proposals, self._reading))

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return (
            f"ModelDiscrimination(model={self._model!r}, "
            f"campaign_id={self._reading.campaign_id!r}, "
            f"correlation={self._reading.correlation!r}, "
            f"interval=({self._reading.lower!r}, {self._reading.upper!r}), "
            f"pairs={self._reading.pairs!r}, proposals={self._proposals!r})"
        )


# ── The reading ──────────────────────────────────────────────────────────────


def mechanism_discrimination_by_model(
    history: Any,
    campaign_id: Any,
    model: Any,
    real_branches: Any,
    *,
    seen_at: datetime | None = None,
) -> ModelDiscrimination:
    """Measure one candidate model's ``mechanism_discrimination`` and persist it.

    Feature 216's sentence as one call: the history handle, the campaign, the
    candidate model and the declared real-branch cohort in; the attributed
    reading out and written down.  It answers the sentence whole — *"persists
    mechanism_discrimination per candidate model before the gate milestone"* — by
    reading the attribution and both halves from one database in one connection,
    so the figure cannot describe a cohort or an author other than the ones the
    tables hold.

    The halves are 214's and are read by 214's functions (:func:`_read_is_half`,
    :func:`_read_oos_half`), so the two features cannot disagree about what a
    branch's in-sample gain is or how a branch's runs become one point; the
    arithmetic is 214's too (:func:`_pearson`, :func:`_interval`,
    :func:`_require_spread`), so there is exactly one definition of §14.1's
    statistic in this member.

    Refuses, in this order, each naming what it is about, and **measures before it
    writes** so a refused reading leaves no row claiming it happened (feature
    123's ordering, for its reason):

    1. an object that is not feature 207's law or store, a malformed campaign id,
       a model that is not a non-blank string, or a cohort that is not a non-empty
       collection of node ids — all before anything touches the disk;
    2. a database holding no ``node_proposal`` table (207's DDL has never run),
       no ``replay_score`` table (``0109`` unreached, so there is no
       out-of-sample half) or no ``campaign`` table (``0111`` unreached);
    3. a campaign the ``campaign`` table does not hold — a reading is a fact
       about a campaign, and writing it onto a row this feature invented would
       fabricate the campaign the number belongs to;
    4. **the attribution** — no ``node`` table (feature 97's revision), a ``node``
       table without ``agent_model_id`` (feature 100's), a declared branch the
       tree does not hold, one whose node carries no model, or one **authored by
       another model**;
    5. a declared branch with no recorded proposal, one whose recorded row
       belongs to another campaign, or one whose snapshot carries no in-sample
       gain — 214's refusals, with 214's class;
    6. a declared branch with no committed run, or runs spanning more than one
       policy version — 214's, likewise;
    7. a cohort the arithmetic cannot answer: fewer than :data:`MINIMUM_PAIRS`,
       a constant series on either side, an exactly perfect correlation, or a
       gain that is not finite — 214's, likewise.

    The ordering of 4 before 5 is deliberate: the attribution is the *cheaper*
    read and the one whose failure means the reading should not be attempted at
    all, while 5's failures are per-branch pairing faults the store reports.  A
    mixed campaign is refused before a missing snapshot, so the operator is told
    the branch is the wrong model rather than that its proposal is absent.

    **Declared is not verified — except here.**  214 cannot check that the
    branches it is handed are real, and this feature cannot either.  What it
    *can* check is that they are one model's, and that is the asymmetry the
    feature is built on: the half of the reading that is verifiable is verified,
    and the half that is not is hashed (:attr:`ModelDiscrimination.cohort_digest`)
    so a published figure's cohort stays auditable afterwards.

    **The write is idempotent by the ``(campaign, model)`` pair**, refreshing
    rather than appending, for 214's reason: §14.1's instrument is run at M2 over
    a cohort that grows as the campaign proposes, so a pair is expected to be
    measured more than once and the table holds the latest reading and nothing
    else.  ``seen_at`` defaults to the current UTC instant at second resolution;
    a caller replaying a recorded run supplies its own.
    """
    path, campaign, candidate, cohort = _validated_reading_arguments(
        history, campaign_id, model, real_branches
    )
    instant = _utc_now() if seen_at is None else seen_at
    count = len(cohort)
    _require_floor(campaign, candidate, count)
    ordered = sorted(cohort)

    with closing(sqlite3.connect(path)) as connection, connection:
        _require_tables(connection, path)
        _require_campaign(connection, campaign)
        _verify_attribution(connection, cohort, candidate, campaign)
        is_half = _read_is_half(connection, cohort, campaign)
        oos_half, policy_version, runs = _read_oos_half(connection, cohort)
        (proposals,) = connection.execute(
            _MODEL_PROPOSALS_SQL, (campaign, candidate)
        ).fetchone()

    # Every value here is already a finite float — both halves were validated at
    # the moment they were read — so the two comprehensions are *ordering*, not
    # validation.  That ordering is the point: the finiteness checks ran during
    # the read, so a `nan` can never reach `_require_spread` and be reported as a
    # constant series, which would be the right refusal for the wrong reason.
    is_gains = [is_half[branch] for branch in ordered]
    oos_gains = [oos_half[branch] for branch in ordered]
    _require_spread(is_gains, name="in-sample", pairs=count)
    _require_spread(oos_gains, name="out-of-sample", pairs=count)
    point = _require_correlation_for(count, is_gains, oos_gains)
    lower, upper = _interval(point, count)
    pairs = tuple(zip(ordered, is_gains, oos_gains))
    digest = _cohort_digest(campaign, candidate, policy_version, pairs)

    reading = ModelDiscrimination(
        campaign_id=campaign,
        model=candidate,
        correlation=point,
        lower=lower,
        upper=upper,
        pairs=count,
        runs=runs,
        proposals=int(proposals),
        policy_version=policy_version,
        cohort_digest=digest,
        seen_at=instant,
    )
    _persist(path, reading)
    return reading


def _validated_reading_arguments(
    history: Any, campaign_id: Any, model: Any, real_branches: Any
) -> tuple[Path, str, str, tuple[str, ...]]:
    """Validate the four arguments, in the feature's order, before any disk read.

    Every refusal here is reachable without opening anything — feature 186's
    reasoning, applied by 214 to its own three: *a refusal that arrived after a
    connection had been made is a validation that ran too late to be one*.

    The handle's check is 214's own :func:`_proposal_history`, imported rather
    than restated.  It raises :class:`DiscriminationCohortError`, and that is
    correct rather than a leak: a handle that is not feature 207's proposal
    history is the same fact with the same repair whoever asks, which is the
    member's own rule for reusing an error class — and 214, the feature that
    already holds that refusal, is a declared dependency of this one.
    """
    path = _proposal_history(history)
    campaign = _validated_campaign_id(campaign_id)
    candidate = _validated_model(model)
    cohort = _validated_cohort(real_branches)
    return path, campaign, candidate, cohort


def _require_floor(campaign: str, model: str, count: int) -> None:
    """Refuse a cohort below §14.1's floor, before anything is opened.

    The floor is checked here rather than after the reads, and for 214's reason
    word for word: every branch in the cohort is required to carry both halves,
    so the cohort's size is the figure's ``n`` whatever the store holds — which
    makes the cheapest and earliest place for this refusal the one where it costs
    no connection and cannot be mistaken for a statement about what the store
    turned out to contain.  It therefore runs *before* the attribution walk,
    which is 214's ordering and not this feature's: the floor is a fact about the
    caller's argument, and it is worth reporting before a database is opened to
    ask about the branches that argument names.

    Raised as :class:`DiscriminationCohortError` — 214's class, unchanged.  The
    repair is 214's (*expand the campaign*), the sentence that explains it is
    214's rule 3, and minting a candidate-model spelling here would be the
    duplicate class the member refuses.  What this function adds is the stratum
    in the message: the operator is told *which model's* cohort is too thin,
    which is a fact only this feature has.
    """
    if count < MINIMUM_PAIRS:
        raise DiscriminationCohortError(
            f"the cohort names {count} real branch(es) of campaign "
            f"{campaign!r} for candidate model {model!r}, and §14.1's figure "
            f"cannot be reported over fewer than {MINIMUM_PAIRS}: the "
            f"arithmetic itself would run — a correlation over two points is "
            f"defined — but rule 3 (*report its interval, not the point*) would "
            f"not, because Fisher's z has no standard error below three pairs "
            f"and no interval at all below four. A cohort the rule cannot be "
            f"applied to is one this feature refuses rather than one it answers "
            f"a bare point about, and the answer is to expand the campaign's "
            f"stratum rather than to print a number (feature 214/216)."
        )


def _require_correlation_for(
    count: int, is_gains: list[float], oos_gains: list[float]
) -> float:
    """The point estimate, refused when it is one the interval cannot be formed at.

    A three-line seam rather than a re-implementation: the arithmetic is 214's
    :func:`_pearson` and the refusal that guards the interval's domain is 214's
    :func:`_require_correlation`.  Spelled as a function only so the call site
    reads the way 214's own does, and so the one place this module's refusals
    differ from 214's — :func:`_require_floor`, which adds the stratum to the
    message — has a sibling whose shape it matches.
    """
    return _require_correlation(_pearson(is_gains, oos_gains), count)


# ── The read half ────────────────────────────────────────────────────────────


def load_model_discrimination(
    history: Any,
    campaign_id: Any,
    model: Any,
) -> ModelDiscrimination | None:
    """Read one ``(campaign, model)`` reading back, or ``None`` when unread.

    The read half of the module's API, and the seam that makes the write
    checkable: a caller that has just measured a pair can read the row and
    compare — the discipline feature 123's guard applies by reading its own half
    back rather than trusting the transaction.

    **The row is *reconstructed*, not merely parsed.**  Every column is fed
    through :class:`ModelDiscrimination`'s validating constructor, which feeds
    them through 214's, so a hand-edited row — a correlation outside ``[-1, 1]``,
    a point outside its own interval, bounds that are not this point's interval
    over this many pairs, fewer than :data:`MINIMUM_PAIRS`, ``runs < pairs``, a
    short digest, a naive stamp, a blank model — fails to load rather than
    loading as a plausible-looking reading.  This feature may not add a column to
    a shared table and therefore has no second row to reconcile against, which is
    the same position 214 is in and the reason it takes the same defence.

    **``None`` means *this campaign has never been measured for this model***,
    which is not *the store is absent* (the handle is required, and a handle with
    no database behind it is refused by 207's own scheme check) and not *the read
    failed* (which raises).  The three-way distinction 214's own
    :func:`load_mechanism_discrimination` states, kept because a caller that
    mistook the first for the second would re-run a measurement it already has —
    and, here, because *this* pair not being measured while another pair of the
    same campaign is, is the ordinary state §14.1 budgets for: two campaigns per
    candidate model, measured one at a time.
    """
    path, campaign = _validated_scope(history, campaign_id)
    candidate = _validated_model(model)
    with closing(sqlite3.connect(path)) as connection:
        if not _has_table(connection, CANDIDATE_TABLE):
            # No table means this feature's measurement has never run in this
            # database.  Answering `None` rather than raising is the state
            # 214 draws for the same reason: a fresh deployment asking what a
            # campaign's per-model reading was is asking a question whose honest
            # answer is *nothing is recorded here*.
            return None
        row = connection.execute(
            f"SELECT {', '.join(_COLUMNS)} FROM {CANDIDATE_TABLE} "
            f"WHERE {CAMPAIGN_ID_COLUMN} = ? AND model = ?",
            (campaign, candidate),
        ).fetchone()
    if row is None:
        return None
    return _reading_from_row(row, campaign, candidate)


def load_model_discriminations(
    history: Any,
    campaign_id: Any,
) -> Mapping[str, ModelDiscrimination]:
    """Read every candidate model's reading of one campaign — §14.1's table.

    The mapping a report of PRD §13 5a — *"M3 results are reported per model
    stratum as well as pooled"* — is tabulated from: one entry per model this
    campaign has been measured for, keyed by the model id **in sorted order**.

    The order is fixed here rather than left to SQLite's row layout, for 215's
    reason: two reads of one unchanged set of rows must produce the same report
    lines, which is what §14.1's reporting rules assume when they compare tables
    across models.

    **Read-only, and a copy.**  The mapping is a
    :class:`~types.MappingProxyType` over a private dict built here, so a caller
    scribbling on what it was handed moves a proxy that refuses writes rather
    than the figure — 215's ``by_model`` guarantee, made the same way.

    **An empty mapping is a real answer and not an error.**  A campaign measured
    for no model yet is the honest state of a campaign at M2 before its first
    reading, and it is deliberately the *same* answer an absent table gets:
    unlike the single-pair read there is no third state to tell apart here,
    because the question a listing asks is *what has been measured* and
    *nothing has* is a complete answer to it whichever of the two reasons
    applies.  214's three-way distinction is kept where it is load-bearing —
    :func:`load_model_discrimination`, where *this pair is unmeasured* has to be
    told from *this store has never been measured in*, because that is the
    question a caller asks before deciding whether to re-measure.

    The scope is validated exactly as the single read's is — the handle, the
    campaign id — so a caller cannot list another store's rows by passing a path
    that is not a proposal history's.
    """
    path, campaign = _validated_scope(history, campaign_id)
    with closing(sqlite3.connect(path)) as connection:
        if not _has_table(connection, CANDIDATE_TABLE):
            return MappingProxyType({})
        rows = connection.execute(
            f"SELECT {', '.join(_COLUMNS)} FROM {CANDIDATE_TABLE} "
            f"WHERE {CAMPAIGN_ID_COLUMN} = ? ORDER BY model ASC",
            (campaign,),
        ).fetchall()
    return MappingProxyType(
        {str(row[1]): _reading_from_row(row, campaign, str(row[1])) for row in rows}
    )


def _validated_scope(history: Any, campaign_id: Any) -> tuple[Path, str]:
    """Validate the scope both reads share: the handle, and the campaign.

    Split out because the *listing* is scoped by the campaign and by nothing
    else — there is no model over which to check — and the alternative that was
    tried first and refused is worth recording so it is not re-invented: passing
    an empty string through a three-argument validator with a note saying not to
    look at the third element.  That version cannot run at all, which is the
    right outcome for a placeholder whose only job was to keep two signatures
    alike: :func:`_validated_model` refuses the empty string, as it must, so the
    "unused" argument was a value the validator had to be told to tolerate.  Two
    functions that each check what they actually use is the honest shape.

    The handle's check is 214's own :func:`_proposal_history`, imported rather
    than restated; see :func:`_validated_reading_arguments` for why its
    :class:`DiscriminationCohortError` is the right class to let through.
    """
    path = _proposal_history(history)
    campaign = _validated_campaign_id(campaign_id)
    return path, campaign


def _reading_from_row(
    row: Any, campaign: str, model: str
) -> ModelDiscrimination:
    """One stored row as a reading, refused by name when it is not one.

    The stamp is parsed back from the ISO-8601 text the column holds, and a value
    that does not parse is refused with :class:`CandidateModelError` rather than
    escaping as a bare ``ValueError`` — the error-vocabulary discipline every
    member seam keeps: a caller's handler for this feature's refusals must catch
    every way the read can decline.

    **The stored campaign and model are checked against the ones asked for**, and
    that is not redundant with the ``WHERE`` clause that selected the row: the
    clause is what the read *intends*, and this is what the row *says*.  A
    mismatch means the row was selected by a value it does not carry — which on
    this schema is a database that has been edited — and a reading rebuilt from
    it would be stamped with an identity it does not hold.  (The listing read
    passes the row's own key back in, so this check is a no-op there and is
    *not* a weakened one: what it pins is the single-pair read.)

    Every other check is :class:`ModelDiscrimination`'s constructor's, which is
    214's; see its docstring.
    """
    (
        stored_campaign,
        stored_model,
        correlation,
        lower,
        upper,
        pairs,
        runs,
        proposals,
        policy_version,
        digest,
        stamp,
    ) = row
    if str(stored_campaign) != campaign or str(stored_model) != model:
        raise CandidateModelError(
            f"a stored {CANDIDATE_TABLE} row carries the pair "
            f"({stored_campaign!r}, {stored_model!r}) rather than the pair "
            f"({campaign!r}, {model!r}) it was selected by: feature 216's row is "
            f"keyed by the campaign and the candidate model, so a row whose key "
            f"does not name what it holds is one a hand has been to — and the "
            f"reading it would rebuild is attributed to a model that did not "
            f"produce it (feature 216)."
        )
    try:
        instant = datetime.fromisoformat(str(stamp))
    except ValueError as error:
        raise CandidateModelError(
            f"a stored {CANDIDATE_TABLE} row for candidate model {model!r} "
            f"carries {stamp!r} as its instant, which is not ISO-8601 text: the "
            f"column holds the moment the reading was taken, and a value that "
            f"does not parse names no moment (feature 216)."
        ) from error
    return ModelDiscrimination(
        campaign_id=campaign,
        model=model,
        correlation=correlation,
        lower=lower,
        upper=upper,
        pairs=pairs,
        runs=runs,
        proposals=proposals,
        policy_version=policy_version,
        cohort_digest=digest,
        seen_at=instant,
    )


# ── The write ────────────────────────────────────────────────────────────────


def _has_table(connection: sqlite3.Connection, table: str) -> bool:
    """Whether the database holds ``table`` yet — a read of ``sqlite_master``."""
    return connection.execute(_TABLE_EXISTS_SQL, (table,)).fetchone() is not None


def _persist(path: Path, reading: ModelDiscrimination) -> None:
    """Write the reading into this member's table, idempotently by the pair.

    Owns the connection because it is the *second* transaction: the attribution,
    the halves and the arithmetic all happened first, in
    :func:`mechanism_discrimination_by_model`'s connection, so a refused reading
    never opens a write at all — feature 123's ordering, and the reason its
    ``guard`` measures before it touches the store.

    ``CREATE TABLE IF NOT EXISTS`` on every call, the contract every store in
    this workspace states: a fresh database and one this build has written to a
    hundred times must both work, and a member-owned table is the one piece of
    DDL this member is entitled to run.  The ``ON CONFLICT`` upsert is 214's,
    widened to the composite key — the grain is the ``(campaign, model)`` pair, so
    a re-reading refreshes the row rather than appending a second one.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with closing(sqlite3.connect(path)) as connection, connection:
        connection.execute(_SCHEMA)
        connection.execute(
            f"INSERT INTO {CANDIDATE_TABLE} ({', '.join(_COLUMNS)}) "
            f"VALUES ({', '.join('?' for _ in _COLUMNS)}) "
            f"ON CONFLICT(campaign_id, model) DO UPDATE SET "
            f"correlation = excluded.correlation, "
            f"interval_lower = excluded.interval_lower, "
            f"interval_upper = excluded.interval_upper, "
            f"pairs = excluded.pairs, runs = excluded.runs, "
            f"proposals = excluded.proposals, "
            f"policy_version = excluded.policy_version, "
            f"cohort_digest = excluded.cohort_digest, "
            f"seen_at = excluded.seen_at",
            (
                reading.campaign_id,
                reading.model,
                reading.correlation,
                reading.lower,
                reading.upper,
                reading.pairs,
                reading.runs,
                reading.proposals,
                reading.policy_version,
                reading.cohort_digest,
                reading.seen_at.isoformat(),
            ),
        )
