"""Feature 21: a non-loopback bind is HTTPS, or no server at all.

*System refuses to bind a non-loopback host unless NULLIUS_API_TLS_CERT
and NULLIUS_API_TLS_KEY name a certificate and key, which returns a
startup error message naming the missing file, and serves HTTPS through
the standard library's ssl module when they do, so a bearer token never
crosses a network in cleartext.*

Each clause is pinned here as its own set of cases, in the order the
sentence states them:

* *refuses to bind a non-loopback host unless…* — the classification
  (:func:`~nullius_api.tls.is_loopback_host`) and the demand
  (:meth:`~nullius_api.tls.TlsConfig.resolve`), including the loopback
  default that needs nothing and the several non-loopback spellings
  that need everything;
* *…returns a startup error message naming the missing file* — one
  plain sentence per failure, naming the variable and the path, with no
  traceback, no file contents, and exit status 2 through the real
  entrypoint;
* *…serves HTTPS through the standard library's ssl module when they
  do* — a live server over a real TLS socket, a cleartext connection to
  the same port failing the handshake, and the token gate still standing
  inside the tunnel.

The certificate is generated by the suite's own fixture
(:func:`conftest.write_self_signed_certificate`) rather than checked in,
and the client verifies it against that exact file — so *serves HTTPS*
is proven by a handshake that would fail against any other certificate,
not by a connection that merely succeeded.
"""

from __future__ import annotations

import http.client
import json
import logging
import os
import socket
import ssl
import subprocess
import sys
import threading
import time
from pathlib import Path

import pytest
from conftest import (
    TEST_TOKENS,
    ssl_client_context,
    token_for,
    write_self_signed_certificate,
    write_token_file,
)
from nullius_api.server import ApiServer
from nullius_api.tls import (
    LOOPBACK_NAMES,
    TLS_CERT_ENV,
    TLS_KEY_ENV,
    TlsConfig,
    TlsConfigError,
    is_loopback_host,
)

from app.module_loader import Application

# -- The classification ------------------------------------------------------------
#
# *Non-loopback* is not a list of dangerous spellings but the complement
# of a list of safe ones, and these cases pin both sides of that line.
# The judgement call the module docstring states — no name is resolved —
# is what makes ``localhost`` loopback and ``api.example.com`` not, even
# though a resolver on some machine would answer both with 127.0.0.1.


@pytest.mark.parametrize(
    "host",
    [
        "127.0.0.1",
        "127.0.0.2",  # the whole 127/8 block is loopback, not just .1
        "::1",
        "[::1]",  # the bracketed spelling a URL uses
        "localhost",
        "LOCALHOST",  # DNS names are case-insensitive
        "localhost.",
        " localhost ",  # whitespace around a value is not a different host
        *sorted(LOOPBACK_NAMES),
    ],
)
def test_a_loopback_spelling_is_loopback(host: str) -> None:
    """Every spelling of *this machine only* classifies as loopback."""
    assert is_loopback_host(host) is True


@pytest.mark.parametrize(
    "host",
    [
        "0.0.0.0",  # every interface — the most exposed bind there is
        "::",
        "192.0.2.10",  # a routable literal
        "10.0.0.5",  # private, but still not loopback
        "api.example.com",  # a name nothing here resolves
        "localhost.example.com",  # a name that merely starts like one
        "127.0.0.1.example.com",  # …and one that names a loopback address
        "",
        "   ",
    ],
)
def test_a_non_loopback_spelling_is_non_loopback(host: str) -> None:
    """Everything not provably loopback counts as exposed.

    Fail-closed on purpose: a hostname that resolves to 127.0.0.1 on
    this machine today is still *not* known to be loopback here, because
    nothing resolves names (see the module docstring).  The cost is a
    certificate demanded for a bind that might not have needed one; the
    cost of the other answer is a token on the wire.
    """
    assert is_loopback_host(host) is False


# -- The demand: loopback needs nothing --------------------------------------------


def test_the_loopback_default_needs_no_certificate() -> None:
    """*Binds 127.0.0.1 by default* is unchanged by this feature: the
    loopback address resolves to a disabled posture and reads neither
    variable."""
    posture = TlsConfig.resolve("127.0.0.1", env={})
    assert posture.enabled is False
    assert posture.cert is None
    assert posture.key is None
    assert posture.scheme == "http"
    assert posture.url(8710) == "http://127.0.0.1:8710"


def test_a_cleartext_bind_is_a_disabled_posture_whatever_the_env_says() -> None:
    """A *loopback* bind configured with a pair stays cleartext rather
    than being silently upgraded: this feature constrains what a
    non-loopback bind may do, and it does not change what a local-only
    deployment serves."""
    posture = TlsConfig.resolve(
        "localhost", env={TLS_CERT_ENV: "/nope/cert.pem", TLS_KEY_ENV: "/nope/k.pem"}
    )
    assert posture.enabled is False
    assert posture.scheme == "http"


# -- The refusal: a non-loopback bind with no pair ---------------------------------


def test_a_non_loopback_bind_with_no_pair_refuses_to_start() -> None:
    """The sentence's own refusal, and it names both variables."""
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve("0.0.0.0", env={})
    message = str(raised.value)
    assert TLS_CERT_ENV in message
    assert TLS_KEY_ENV in message
    assert "0.0.0.0" in message
    assert "127.0.0.1" in message  # the repair


@pytest.mark.parametrize(
    ("env", "clause"),
    [
        # Both variables set to nothing: the plural subject takes the
        # plural verb, and the missing noun is the pair.
        ({}, f"{TLS_CERT_ENV} and {TLS_KEY_ENV} name no certificate and key"),
        # One variable set: the subject is singular, and the sentence
        # names only that half — an operator sent to look at a file they
        # already configured has been misled.
        (
            {TLS_KEY_ENV: "/etc/key.pem"},
            f"{TLS_CERT_ENV} names no certificate,",
        ),
        (
            {TLS_CERT_ENV: "/etc/cert.pem"},
            f"{TLS_KEY_ENV} names no private key,",
        ),
    ],
)
def test_the_refusal_agrees_with_what_was_and_was_not_configured(
    env: dict[str, str], clause: str
) -> None:
    """The operator reads this once, at startup, with no other clue.

    The verb agrees with its subject and the noun agrees with how many
    variables are missing, so the sentence never reads as though neither
    variable were set when only one was.
    """
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve("0.0.0.0", env=env)
    assert clause in str(raised.value)


@pytest.mark.parametrize(
    "missing",
    [TLS_CERT_ENV, TLS_KEY_ENV],
)
def test_a_half_configured_pair_refuses_to_start(missing: str) -> None:
    """Either half alone is the same refusal — and the message names the
    one that *was* given, so an operator who set only the key can see
    it was seen."""
    given = TLS_KEY_ENV if missing == TLS_CERT_ENV else TLS_CERT_ENV
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve("0.0.0.0", env={given: "/etc/its-here.pem"})
    message = str(raised.value)
    assert missing in message
    assert "/etc/its-here.pem" in message


def test_a_non_loopback_bind_with_a_missing_certificate_names_the_file(
    tmp_path: Path,
) -> None:
    """*A startup error message naming the missing file* — the path the
    operator set, not a traceback and not a generic sentence."""
    absent = tmp_path / "no-such-certificate.pem"
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve(
            "0.0.0.0", env={TLS_CERT_ENV: str(absent), TLS_KEY_ENV: "/etc/key.pem"}
        )
    message = str(raised.value)
    assert str(absent) in message
    assert TLS_CERT_ENV in message
    assert "does not exist" in message


def test_a_non_loopback_bind_with_a_missing_key_names_the_file(
    tmp_path: Path, certificate_pair: tuple[str, str]
) -> None:
    """The same for the key: the certificate is fine and the key is not
    there, and the refusal says which file is at fault."""
    absent = tmp_path / "no-such-key.pem"
    certificate, _ = certificate_pair
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve(
            "0.0.0.0", env={TLS_CERT_ENV: certificate, TLS_KEY_ENV: str(absent)}
        )
    assert str(absent) in str(raised.value)


def test_a_certificate_that_cannot_be_read_is_refused_by_name(
    tmp_path: Path, certificate_pair: tuple[str, str]
) -> None:
    """A path that is a directory is one of the ways the file is not
    there *as a file*, and it is refused with the (OSError) name rather
    than a traceback."""
    certificate, key = certificate_pair
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve(
            "0.0.0.0", env={TLS_CERT_ENV: str(tmp_path), TLS_KEY_ENV: key}
        )
    message = str(raised.value)
    assert str(tmp_path) in message
    assert "directory" in message
    assert certificate  # the working pair is untouched by the failure


def test_files_that_are_not_a_certificate_and_key_are_refused(
    tmp_path: Path,
) -> None:
    """The posture is established by *loading* the pair, so two files
    that exist and are not a usable certificate and key are refused at
    startup rather than at the first handshake."""
    cert = tmp_path / "not-a-cert.pem"
    key = tmp_path / "not-a-key.pem"
    cert.write_text("this is not a certificate\n", encoding="utf-8")
    key.write_text("this is not a key\n", encoding="utf-8")
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve(
            "0.0.0.0", env={TLS_CERT_ENV: str(cert), TLS_KEY_ENV: str(key)}
        )
    message = str(raised.value)
    assert str(cert) in message
    assert str(key) in message
    # Neither file's contents are echoed back.
    assert "this is not a certificate" not in message


def test_a_key_that_does_not_match_the_certificate_is_refused(
    tmp_path: Path, certificate_pair: tuple[str, str]
) -> None:
    """A certificate and *another* key is the case a deployment is most
    likely to hit by hand, and it is refused before the bind like every
    other unusable pair."""
    certificate, _ = certificate_pair
    _, other_key = write_self_signed_certificate(tmp_path, name="other")
    with pytest.raises(TlsConfigError) as raised:
        TlsConfig.resolve(
            "0.0.0.0", env={TLS_CERT_ENV: certificate, TLS_KEY_ENV: other_key}
        )
    assert TLS_CERT_ENV in str(raised.value)


def test_no_refusal_carries_a_traceback(certificate_pair: tuple[str, str]) -> None:
    """Every refusal this module writes is one sentence for an operator:
    no traceback marker, and no ``.py`` file name."""
    cases: list[dict[str, str]] = [
        {},
        {TLS_CERT_ENV: "/nope/c.pem"},
        {TLS_KEY_ENV: "/nope/k.pem"},
        {TLS_CERT_ENV: "/nope/c.pem", TLS_KEY_ENV: "/nope/k.pem"},
    ]
    for env in cases:
        with pytest.raises(TlsConfigError) as raised:
            TlsConfig.resolve("0.0.0.0", env=env)
        message = str(raised.value)
        assert "Traceback" not in message
        assert ".py" not in message
        assert certificate_pair  # the fixture pair is irrelevant here


# -- Serving: the standard library's ssl module -------------------------------------
#
# These cases run a *real* server on a real socket and speak TLS to it
# with a verifying client.  Loopback is the only interface a test may
# bind, so the posture is handed to the server explicitly — the
# constructor wraps exactly the posture it is given — which is how the
# non-loopback branch is exercised without a non-loopback address.


class _Answer:
    """An endpoint shaped like the no-argument GET routes the core serves."""

    route = "/metrics/fdr-deploy"

    def get(self) -> dict:
        return {"history": []}


class _TlsBoot:
    """Boot one HTTPS server per case on an ephemeral loopback port."""

    def __init__(self) -> None:
        self._servers: list[tuple[ApiServer, threading.Thread]] = []

    def __call__(self, tls: TlsConfig) -> ApiServer:
        application = Application(
            components={"ops-fdr-deploy": _Answer()}, order=("ops-fdr-deploy",)
        )
        server = ApiServer(
            ("127.0.0.1", 0), application, TEST_TOKENS, tls=tls
        )
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        self._servers.append((server, thread))
        return server

    def shutdown(self) -> None:
        for server, thread in self._servers:
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)


@pytest.fixture
def tls_boot():
    runner = _TlsBoot()
    yield runner
    runner.shutdown()


def _https_get(
    server: ApiServer, certificate: str, path: str, scope: str = "metrics:read"
) -> tuple[int, dict]:
    """One HTTPS GET, verified against the fixture certificate."""
    context = ssl_client_context(certificate)
    connection = http.client.HTTPSConnection(
        "127.0.0.1", server.server_address[1], timeout=10, context=context
    )
    try:
        connection.request(
            "GET", path, headers={"Authorization": f"Bearer {token_for(scope)}"}
        )
        response = connection.getresponse()
        return response.status, json.loads(response.read().decode("utf-8"))
    finally:
        connection.close()


def test_the_listening_socket_is_wrapped_so_the_bind_serves_https(
    tls_boot, certificate_pair: tuple[str, str]
) -> None:
    """*Serves HTTPS through the standard library's ssl module*: the
    server's own socket is an ``SSLSocket`` — not a cleartext socket
    with TLS arranged somewhere else — and a request over it answers."""
    certificate, key = certificate_pair
    server = tls_boot(TlsConfig(host="0.0.0.0", cert=certificate, key=key, enabled=True))
    assert isinstance(server.socket, ssl.SSLSocket)
    assert server.tls.enabled is True
    assert server.tls.scheme == "https"

    status, body = _https_get(server, certificate, "/metrics/fdr-deploy")
    assert status == 200
    # The stand-in endpoint above answers this body; the composed
    # application's own derived reads are pinned in test_metrics_routes.
    assert body == {"history": []}


def test_a_cleartext_connection_to_an_https_bind_fails_the_handshake(
    tls_boot, certificate_pair: tuple[str, str]
) -> None:
    """The purpose clause, made observable: a plain HTTP client talking
    to an HTTPS bind gets no answer at all — the token never crosses in
    cleartext because there is no cleartext response to carry it."""
    certificate, key = certificate_pair
    server = tls_boot(TlsConfig(host="0.0.0.0", cert=certificate, key=key, enabled=True))

    connection = http.client.HTTPConnection(
        "127.0.0.1", server.server_address[1], timeout=10
    )
    try:
        with pytest.raises((http.client.HTTPException, OSError)):
            connection.request("GET", "/healthz")
            connection.getresponse()
    finally:
        connection.close()


def test_the_handshake_would_fail_against_the_wrong_certificate(
    tls_boot, certificate_pair: tuple[str, str], tmp_path: Path
) -> None:
    """*Serves HTTPS* means *with the configured certificate*: a client
    that trusts a different one refuses the connection, so the case
    above cannot pass against a server that merely wrapped its socket in
    something."""
    certificate, key = certificate_pair
    other_cert, _ = write_self_signed_certificate(tmp_path, name="elsewhere")
    server = tls_boot(TlsConfig(host="0.0.0.0", cert=certificate, key=key, enabled=True))

    context = ssl_client_context(other_cert)
    connection = http.client.HTTPSConnection(
        "127.0.0.1", server.server_address[1], timeout=10, context=context
    )
    try:
        with pytest.raises(ssl.SSLError):
            connection.request("GET", "/healthz")
            connection.getresponse()
    finally:
        connection.close()


def test_the_token_gate_still_stands_inside_the_tunnel(
    tls_boot, certificate_pair: tuple[str, str]
) -> None:
    """HTTPS is the transport, not a substitute for the credential: an
    unauthenticated request over TLS is answered 401 exactly as it is
    over cleartext, and the token is what the tunnel protects."""
    certificate, key = certificate_pair
    server = tls_boot(TlsConfig(host="0.0.0.0", cert=certificate, key=key, enabled=True))

    context = ssl_client_context(certificate)
    connection = http.client.HTTPSConnection(
        "127.0.0.1", server.server_address[1], timeout=10, context=context
    )
    try:
        connection.request("GET", "/metrics/fdr-deploy")
        response = connection.getresponse()
        assert response.status == 401
        assert json.loads(response.read())["error"]["code"] == "missing_token"
    finally:
        connection.close()


def test_a_server_built_on_a_non_loopback_address_demands_the_pair(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A hand-built ``ApiServer`` cannot skip the question: given an
    address that is not loopback and no posture, it resolves one over
    the environment and refuses the same way — so *refuses to bind* is a
    property of the server, not a check its callers remember."""
    monkeypatch.delenv(TLS_CERT_ENV, raising=False)
    monkeypatch.delenv(TLS_KEY_ENV, raising=False)
    with pytest.raises(TlsConfigError):
        ApiServer(
            ("0.0.0.0", 0),
            Application(components={}, order=()),
            TEST_TOKENS,
        )


def test_a_refused_bind_leaves_no_socket_behind(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The posture is resolved *before* ``super().__init__`` binds, so a
    refusal costs no socket: were it resolved after, the refusal would
    leak a listening socket on the address that was just refused."""
    monkeypatch.delenv(TLS_CERT_ENV, raising=False)
    monkeypatch.delenv(TLS_KEY_ENV, raising=False)
    before = _open_socket_count()
    with pytest.raises(TlsConfigError):
        ApiServer(("0.0.0.0", 0), Application(components={}, order=()), TEST_TOKENS)
    assert _open_socket_count() == before


def _open_socket_count() -> int:
    """How many file descriptors this process holds (Linux only).

    Read off ``/proc/self/fd``, which exists on the platform this
    workspace runs on; elsewhere the case is skipped rather than
    asserted against a number it cannot read.
    """
    directory = Path("/proc/self/fd")
    if not directory.exists():  # pragma: no cover - non-Linux
        pytest.skip("no /proc on this platform")
    return len(list(directory.iterdir()))


def test_a_cleartext_probe_of_an_https_bind_is_logged_as_one_line(
    tls_boot, certificate_pair: tuple[str, str], caplog
) -> None:
    """A failed handshake does not vanish and does not print a traceback.

    The base class's accept loop swallows the :class:`ssl.SSLError` a
    cleartext probe raises, so without a line here the event leaves no
    trace at all; and the base class's error reporter would print a
    whole stack, which on an HTTPS bind is noise for a routine probe.
    One line naming the fault is what an operator can act on.
    """
    certificate, key = certificate_pair
    server = tls_boot(TlsConfig(host="0.0.0.0", cert=certificate, key=key, enabled=True))

    connection = http.client.HTTPConnection(
        "127.0.0.1", server.server_address[1], timeout=10
    )
    try:
        with caplog.at_level(logging.WARNING, logger="nullius_api.server"):
            # Nothing to wait for on this side: the client fails the
            # handshake and the *server's* thread reports it a moment
            # later, so the record is polled for below rather than
            # asserted on the instant the client gave up.
            with pytest.raises((http.client.HTTPException, OSError)):
                connection.request("GET", "/healthz")
                connection.getresponse()
            deadline = time.monotonic() + 10.0
            while time.monotonic() < deadline and not caplog.records:
                time.sleep(0.05)
    finally:
        connection.close()

    messages = [record.getMessage() for record in caplog.records]
    assert any("TLS handshake" in message for message in messages), messages
    assert all("Traceback" not in message for message in messages)


def test_a_client_that_rejects_the_certificate_is_logged_as_one_line(
    tls_boot, certificate_pair: tuple[str, str], tmp_path: Path, caplog
) -> None:
    """The *second* shape of a handshake failure, and the reason the
    base class's reporting had to be replaced rather than left alone.

    A TLS 1.3 client only announces its verification failure *after*
    completing the handshake — so on a fast localhost this arrives while
    the handler is reading the request line, not during ``accept``, and
    the base class would print a stack naming this module and a thread
    for a fault that is entirely the caller's.  One line, no stack.
    """
    certificate, key = certificate_pair
    other_cert, _ = write_self_signed_certificate(tmp_path, name="distrusted")
    server = tls_boot(TlsConfig(host="0.0.0.0", cert=certificate, key=key, enabled=True))

    with caplog.at_level(logging.WARNING, logger="nullius_api.server"):
        raw = socket.create_connection(("127.0.0.1", server.server_address[1]), timeout=10)
        try:
            ssl_client_context(other_cert).wrap_socket(
                raw, server_hostname="127.0.0.1"
            )
        except ssl.SSLError:
            pass
        finally:
            raw.close()
        deadline = time.monotonic() + 10.0
        while time.monotonic() < deadline and not caplog.records:
            time.sleep(0.05)

    messages = [record.getMessage() for record in caplog.records]
    assert messages, "the failure left no trace at all"
    assert all("Traceback" not in message for message in messages)
    assert all(".py" not in message for message in messages)


def test_a_disabled_posture_wraps_nothing(tls_boot) -> None:
    """The loopback case is untouched: the posture hands back the very
    socket it was given, so feature 4's server is bit-for-bit what it
    was — same plain ``socket``, same cleartext answers."""
    server = tls_boot(TlsConfig.resolve("127.0.0.1", env={}))
    assert not isinstance(server.socket, ssl.SSLSocket)

    connection = http.client.HTTPConnection(
        "127.0.0.1", server.server_address[1], timeout=10
    )
    try:
        connection.request("GET", "/healthz")
        assert connection.getresponse().status == 200
    finally:
        connection.close()


def test_wrap_returns_the_same_socket_when_disabled() -> None:
    """The unit behind the case above: ``wrap`` on a disabled posture is
    the identity, so nothing in the serving path can wrap by accident."""
    probe = socket.socket()
    try:
        assert TlsConfig.resolve("localhost", env={}).wrap(probe) is probe
    finally:
        probe.close()


# -- The whole entrypoint, refusing to start (exit status 2) ------------------------


def _bootstrap_env(database_url: str, token_file: str) -> dict[str, str]:
    """The subprocess environment, minus anything TLS-related.

    Built by hand rather than through :mod:`test_main`'s helper because
    these cases are about what happens when a *non-loopback* host is
    named and the TLS variables are not: ``NULLIUS_API_HOST`` is the
    only variable added, and every certificate variable is removed
    rather than inherited from whatever shell ran the suite.
    """
    from app.module_loader import workspace_scan_roots

    repo_root = Path(__file__).resolve().parents[3]
    entries = [str(repo_root / "src"), *(str(root) for root in workspace_scan_roots())]
    environment = dict(os.environ)
    environment.update(
        {
            "DATABASE_URL": database_url,
            "NULLIUS_API_HOST": "0.0.0.0",
            "NULLIUS_API_PORT": "0",
            "NULLIUS_API_TOKENS_FILE": token_file,
            "PYTHONPATH": ":".join(entries),
        }
    )
    environment.pop(TLS_CERT_ENV, None)
    environment.pop(TLS_KEY_ENV, None)
    return environment


def test_the_entrypoint_refuses_to_start_on_a_non_loopback_bind(
    test_database_url: str, tmp_path: Path
) -> None:
    """The real ``python -m nullius_api``, told to bind every interface
    with no certificate configured: exit status 2 and one plain sentence
    naming both variables.  Run as a subprocess because *refuses to
    bind* is a claim about the process — it must be the process that
    exits, not a helper that raised."""
    token_file = write_token_file(tmp_path / "tokens.json")
    process = subprocess.run(
        [sys.executable, "-m", "nullius_api"],
        env=_bootstrap_env(test_database_url, token_file),
        capture_output=True,
        text=True,
        timeout=120,
        check=False,  # the exit status is the assertion
    )
    assert process.returncode == 2
    assert TLS_CERT_ENV in process.stderr
    assert TLS_KEY_ENV in process.stderr
    assert "0.0.0.0" in process.stderr
    assert "Traceback" not in process.stderr
    assert str(Path.cwd()) not in process.stderr  # no filesystem path


def test_the_entrypoint_refuses_to_start_with_a_missing_certificate_file(
    test_database_url: str, tmp_path: Path
) -> None:
    """*A startup error message naming the missing file* — end to end,
    as an operator would see it: the path they configured, on standard
    error, with the exit status the token file's own refusal uses."""
    token_file = write_token_file(tmp_path / "tokens.json")
    absent = tmp_path / "gone.pem"
    environment = _bootstrap_env(test_database_url, token_file)
    environment[TLS_CERT_ENV] = str(absent)
    environment[TLS_KEY_ENV] = str(tmp_path / "gone-key.pem")

    process = subprocess.run(
        [sys.executable, "-m", "nullius_api"],
        env=environment,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,  # the exit status is the assertion
    )
    assert process.returncode == 2
    assert str(absent) in process.stderr
    assert TLS_CERT_ENV in process.stderr
    assert "Traceback" not in process.stderr


def test_the_entrypoint_serves_https_when_the_pair_is_there(
    test_database_url: str, tmp_path: Path
) -> None:
    """The sentence's success case, end to end.

    The subprocess is told to bind ``0.0.0.0`` — a non-loopback host,
    which is the case the feature is about — *with* the pair
    configured, and the test reaches it over ``127.0.0.1``, which the
    any-interface bind answers.  It is a real HTTPS server: the
    connection is verified against the fixture's own certificate, so a
    process that bound cleartext would fail the handshake rather than
    quietly pass.
    """
    certificate, key = write_self_signed_certificate(tmp_path)
    token_file = write_token_file(tmp_path / "tokens.json")
    port = _free_port()
    environment = _bootstrap_env(test_database_url, token_file)
    environment[TLS_CERT_ENV] = certificate
    environment[TLS_KEY_ENV] = key
    environment["NULLIUS_API_PORT"] = str(port)

    process = subprocess.Popen(
        [sys.executable, "-m", "nullius_api"],
        env=environment,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    try:
        status, body = _poll_https(port, certificate, "/metrics/fdr-deploy")
        assert status == 200
        assert body == {
            "history": [],
            "campaign_id": None,
            "fdr_deploy": None,
            "computed_at": None,
        }
        # …and the server is still serving, not exited after one answer.
        assert process.poll() is None
    finally:
        process.terminate()
        try:
            process.wait(timeout=10)
        except subprocess.TimeoutExpired:  # pragma: no cover - defensive
            process.kill()
            process.wait(timeout=10)


def _free_port() -> int:
    """A port the kernel confirms free — bound then released, so the
    entrypoint can take it back."""
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def _poll_https(port: int, certificate: str, path: str) -> tuple[int, dict]:
    """Poll an HTTPS server until it answers, then return its answer.

    Polling a *verified* HTTPS connection means a server that had not
    yet finished binding, or that bound cleartext, keeps being retried
    until the deadline — the assertion is on the answer, not on the
    first connection attempt.
    """
    context = ssl_client_context(certificate)
    deadline = time.monotonic() + 60.0
    last: Exception | None = None
    while time.monotonic() < deadline:
        try:
            connection = http.client.HTTPSConnection(
                "127.0.0.1", port, timeout=5, context=context
            )
            try:
                connection.request(
                    "GET",
                    path,
                    headers={"Authorization": f"Bearer {token_for('metrics:read')}"},
                )
                response = connection.getresponse()
                return response.status, json.loads(response.read().decode("utf-8"))
            finally:
                connection.close()
        except OSError as exc:
            last = exc
            time.sleep(0.3)
    raise AssertionError(f"the HTTPS entrypoint never answered: {last!r}")
