"""The weights a node was authored under — feature 204's first half.

app_spec.xml, "LLM Provider Tiering & Agent Pinning", feature 204: *System
persists ``agent_ckpt_hash`` for self-hosted weights plus ``agent_sampling``
recording temperature, top_p, thinking and seed.*  :mod:`providers._pinning`
pins *which model*; this module pins *which weights*, which is a different
question with a different answer, and the column exists because the two answers
diverge.

Why the weights need their own column
-------------------------------------

A ``ModelPin`` names a provider, a model and a version, and §14.1's mitigation 2
is explicit that whether a given version string is genuinely immutable *"is a
procurement fact, not a parseable one"* — this member can enforce the triple's
structure and nothing beyond it.  So there is a residue: a triple can be
perfectly well-formed and still describe a target the provider may re-point.

Mitigation 1 is the answer for the campaigns that feed M3, and it is the reason
this column exists:

    **Self-host open weights** for the campaigns that feed M3. MIT-licensed
    checkpoints with FP8 quants and published vLLM configs make
    ``agent_ckpt_hash`` a real hash, not a promise.

When the deployment runs the weights itself, the weights are bytes on a disk
and the hash of those bytes is the identity — no procurement promise, no
provider's word, no re-pointing.  It is the strongest of the three mitigations
because it is the only one that does not depend on anybody else's behaviour.

The nullability *is* the fact
-----------------------------

Architecture §9.1's comment on the column is ``-- non-null for self-hosted
weights``, and the PRD's provenance block says the same in the same words.  So
this module reads the null as a **positive fact** rather than an absence, and
``0115``'s docstring argues the same from the schema's side: *"unlike 0114's
NULLs this one is not an absence but a positive fact ... NULL records
'hosted-API weights, no local checkpoint to hash'"*.

That reading is what makes the store's refusals necessary rather than
fastidious.  If ``None`` meant "unknown" then writing ``None`` over a recorded
hash would lose information and nothing more; because ``None`` means
*hosted-API weights*, writing it over a recorded hash **asserts** something —
that this node's weights are a provider's to change — about a node whose
weights were previously pinned exactly.  Two nodes generated by one checkpoint
would then read as two weights, and §14.1's mitigation 3 (record and stratify)
would be stratifying on a column that no longer distinguishes them.  So
:func:`hosted_api_weights` exists to make the hosted case a *value a caller
states* rather than a field a caller omits, and the store refuses to let one
overwrite the other.

What a hash is, and the one spelling refused
--------------------------------------------

``CHAR(64)`` — the sha256 hex digest, the same shape feature 98's ``code_hash``
and feature 99's provenance triple take.  :func:`require_agent_ckpt_hash`
accepts 64 hex characters in either case and folds rather than refuses the
uppercase spelling, which is the rule :func:`artifacts.canonical_code_hash`
established for ``code_hash``: ``"AB…"`` and ``"ab…"`` are one digest written
two ways, and a store that treated them as two would let the same checkpoint
appear as two weight strata — the duplicate-stratum failure the folding exists
to prevent.

The one spelling refused *by name*, beyond the malformed ones, is the
``sha256:``-prefixed form.  ``registry/repo@sha256:…`` is how a container
reference carries its digest, and the prefix is part of the reference rather
than part of the digest: a column holding one would hold a value no comparison
against another node's hash could ever equal, and the refusal says so instead
of silently stripping a prefix a caller may have meant.  This is the same
refusal :func:`artifacts.canonical_code_hash` makes for the same input, and
:mod:`canary._image` is the member that parses the prefixed form properly — a
reader that needs it should reach for that parser rather than have this column
guess.

Stdlib-only: a frozenset of hex digits and one function.  The store that writes
the column is :mod:`providers._pin_store`.
"""

from __future__ import annotations

from typing import Any

from ._pin_errors import CkptHashMalformedError

__all__ = [
    "AGENT_CKPT_HASH_COLUMN",
    "CKPT_HASH_LENGTH",
    "HOSTED_API_CKPT_HASH",
    "hosted_api_weights",
    "require_agent_ckpt_hash",
]

#: The ``node`` column the digest is persisted into — feature 100's, spelled by
#: the spec's own schema block and created by revision ``0115``.
AGENT_CKPT_HASH_COLUMN = "agent_ckpt_hash"

#: ``CHAR(64)`` — the length of a stored checkpoint hash, and the length the
#: canonical spelling is checked against.  A sha256 hex digest and nothing else:
#: the width every ``CHAR(64)`` provenance column in §9.1 shares, and the width
#: :func:`artifacts.canonical_code_hash` checks ``code_hash`` against for the
#: same reason.
CKPT_HASH_LENGTH = 64

#: The hexdigest alphabet, lowercase — the case every accepted spelling is
#: folded to before it is compared against this set.
_HEX_DIGITS = frozenset("0123456789abcdef")

#: The spelling an *image reference* carries its digest in, refused by name.
#: ``registry/repo@sha256:…`` names the same bytes as the digest alone, but the
#: prefix belongs to the reference and not to the digest — so a column holding
#: one would hold a value no other node's hash could ever equal, and a store
#: that quietly stripped it would be accepting a spelling the ledger's
#: provenance validator and :func:`artifacts.canonical_code_hash` both refuse.
_DIGEST_PREFIX = "sha256:"

#: The value ``agent_ckpt_hash`` holds for *hosted-API weights* — ``NULL``,
#: spelled as a named constant so the hosted case is a state a caller **states**
#: rather than a field a caller forgets.  ``None`` is the whole of it: §9.1's
#: comment is ``non-null for self-hosted weights``, so the null is the record
#: that this node's weights are a provider's and there is no local checkpoint to
#: hash.  See :func:`hosted_api_weights`.
HOSTED_API_CKPT_HASH: None = None


def hosted_api_weights() -> None:
    """The ``agent_ckpt_hash`` of a node authored by hosted-API weights.

    Returns ``None``, and exists so that the hosted-API case has a *name* at
    every call site.  ``persist_weights(node, ckpt_hash=None, ...)`` and
    ``persist_weights(node, ckpt_hash=hosted_api_weights(), ...)`` pass the same
    value, and that is the point: the two read differently to a person, and the
    second says *this was a decision* while the first may be a field the caller
    never thought about.

    It is worth a function because the null is load-bearing.  §9.1 records it as
    *"non-null for self-hosted weights"*, so the null is a fact about where the
    weights came from rather than a missing measurement, and the store refuses
    to let a hosted-API record overwrite a recorded checkpoint hash for that
    reason: the overwrite would not record less, it would assert that a node
    whose weights were pinned exactly is one whose weights are a provider's to
    change.  A caller that has genuinely moved a node to hosted-API weights is a
    caller that has a *different* node — the weights that produced the stored
    scores are the ones on the row, and the new deployment's are not.

    Returns ``None`` rather than a sentinel object so the value that lands in
    the column is the one the schema declares, and so a caller comparing against
    ``is None`` — the way every reader of a nullable column does — gets the
    answer it expects.
    """
    return HOSTED_API_CKPT_HASH


def require_agent_ckpt_hash(value: Any) -> str:
    """Return ``value`` as the canonical 64-character checkpoint hash, or refuse it.

    §9.1 types the column ``CHAR(64)`` and the digest of a set of weights is a
    sha256 hex digest, so the canonical form is exactly that: 64 lowercase hex
    characters.  Case is *folded*, not refused — ``"AB…"`` and ``"ab…"`` are one
    digest written two ways, and a store that treated them as two would let one
    checkpoint appear as two weight strata, which is the heterogeneity §14.1's
    mitigation 3 exists to make visible, manufactured by the reader instead.

    Anything else is refused by name: a truncated or short hash, a
    ``sha256:``-prefixed image reference, a non-hex token, a non-string.  The
    refusal is loud because the alternative is silent — a node whose weights
    cannot be stated cannot be stratified by them, so a store that guessed would
    place every such node in a weight stratum it invented.

    A digest in the prefixed form is refused rather than stripped, and the
    message says which parser wants that shape: ``canary``'s
    :func:`~canary.parse_image_pin` reads a container reference properly, and
    this module is not the place to re-derive one — a column that held a
    reference where a digest belongs would compare unequal to every other node's
    hash while *looking* like it named a checkpoint.

    ``None`` is not accepted here, and the reason is about *doors* rather than
    about the null's meaning.  This function's job is to read a hash, so its
    input is a hash; hosted-API weights are the case where there is no hash to
    read, and they are recorded through :func:`hosted_api_weights` (see
    :class:`providers.AgentWeights`) instead.  A caller that hands ``None``
    *here* has not stated the hosted case — it has asked this function to name a
    checkpoint and named none, and
    :class:`~providers.CkptHashMalformedError` is the honest report for that.

    That is not a claim that the null in the column is meaningless: the module
    docstring above argues the opposite, and the two are consistent because the
    meanings live in different places.  ``None`` is a positive fact *about a
    node* — the row records hosted-API weights — and the store reads it as one.
    It is not a value *for a hash*, which is all this function can parse, and a
    bare-value parser that answered "hosted" for it would be making a claim
    about a row it has never seen: the same input reaches it from a caller who
    simply forgot an argument.
    """
    if not isinstance(value, str):
        raise CkptHashMalformedError(
            f"an agent_ckpt_hash must be a string — the sha256 hex digest §9.1 "
            f"stores as CHAR(64) — got {type(value).__name__} {value!r}. The "
            f"checkpoint hash is the identity §14.1's mitigation 1 buys: "
            f"self-hosting the open weights makes it a real hash rather than a "
            f"provider's promise, and a value that is not one names no weights "
            f"a stratification could group by. Hosted-API weights have no "
            f"checkpoint to hash — record those through "
            f"hosted_api_weights() rather than by handing a non-hash here."
        )
    text = value.strip().casefold()
    if text.startswith(_DIGEST_PREFIX):
        raise CkptHashMalformedError(
            f"an agent_ckpt_hash must be the digest itself, not the "
            f"{_DIGEST_PREFIX!r}-prefixed image-reference spelling, got "
            f"{value!r}. The prefix belongs to a container reference "
            f"(``registry/repo@{_DIGEST_PREFIX}…``) and not to the digest — "
            f"canary.parse_image_pin is the parser that reads that form — so a "
            f"column holding the prefixed spelling would hold a value no other "
            f"node's checkpoint hash could ever equal, while looking like it "
            f"named one. Store the {CKPT_HASH_LENGTH} hex characters."
        )
    if len(text) != CKPT_HASH_LENGTH or any(char not in _HEX_DIGITS for char in text):
        raise CkptHashMalformedError(
            f"an agent_ckpt_hash must be {CKPT_HASH_LENGTH} hexadecimal "
            f"characters — got {value!r} (length {len(text)}). §9.1 types the "
            f"column CHAR(64) and the digest of a checkpoint is "
            f"sha256(weights).hexdigest(), so a truncated hash, a non-hex token "
            f"or a padded value is a weight identity nothing stored could ever "
            f"equal — and a checkpoint that cannot be compared is a node the "
            f"model-stratum ablation will place in a stratum of its own."
        )
    return text
