"""The registry that turns a pinned model into a bound live provider.

The live-providers addition has two backends — the Anthropic Messages backend
of :mod:`providers._anthropic` and the OpenAI-compatible backend of
:mod:`providers._openai_compat` — and a pin (feature 203's
:class:`~providers.ModelPin`, a ``provider/model/version`` triple) is the one
piece of configuration the rest of the system holds about which model should
serve a call.  This module is the seam between the two: :func:`live_provider`
reads a pin, decides which backend serves the vendor it names, finds that
vendor's credential in the environment, and answers a constructed provider —
so a caller that holds a pin never has to know which backend covers which
vendor, which environment variable holds which key, or which of the two
construction signatures it needs.  That decision is made here, once, rather
than re-decided (and re-forgotten) by every caller.

**One variable per vendor, and the prefix is load-bearing.**  Each vendor's
credential lives in its own environment variable — see
:data:`LIVE_PROVIDER_ENV_VARS` — and every one of them is namespaced
``NULLIUS_``: ``NULLIUS_ANTHROPIC_API_KEY``, ``NULLIUS_OPENAI_API_KEY``,
``NULLIUS_DEEPSEEK_API_KEY`` and ``NULLIUS_GOOGLE_API_KEY``, with
``NULLIUS_SELF_HOSTED_BASE_URL`` for the one vendor whose destination is
configuration rather than a default, and an optional
``NULLIUS_SELF_HOSTED_API_KEY`` alongside it.  The prefix is not decoration:
claw-forge itself reads a bare ``ANTHROPIC_API_KEY``, and a research member
that read that name would spend the harness's credential on a research call.
This module reads only the ``NULLIUS_``-prefixed names — a bare
``ANTHROPIC_API_KEY`` in the environment is invisible to it by construction,
not by a check that could drift.

**A missing variable is a configuration error, named and never rendered.**
A vendor whose variable is absent or empty is a deployment gap the caller can
fix, so it leaves as :class:`~providers.ProviderNotConfiguredError` *naming
the variable* — ``NULLIUS_OPENAI_API_KEY is not set`` — and never its value.
The distinction matters in both directions: the operator reading the refusal
needs the variable's name to set it, and a refusal is one of the three places
a credential must never reach (the other two are a repr and a log line), so
even an empty value is described as empty rather than printed.

**The wire model is the pin's model; the version is provenance.**  A pin
carries three parts, but only ``model`` reaches the wire — a pinned model is
served by its name, and the version is the record of which snapshot a
campaign ran against, checked after the fact by :func:`require_served` rather
than sent to the vendor.  The backend is therefore constructed for
``pin.model`` and for that alone.

**The check that catches a silently-swapped model.**  :func:`require_served`
is this feature's second half and the reason the pin carries a version at
all.  Architecture §14.1 documents the failure it exists for: DeepSeek
retired ``deepseek-v4-flash`` in September 2026 while continuing to accept
the id and serving V4.1-Flash underneath it, so two campaigns under one model
string were generated by two different models.  A completion names the model
that actually served it, and :func:`require_served` compares that name to the
pin's: a serving model equal to ``pin.model``, or equal to ``pin.model``
followed by ``-`` and ``pin.version`` (the exact dated snapshot the pin
names, the shape a vendor uses for "the same model, pinned") is admitted
unchanged; anything else — a different model, or a different snapshot of the
same model — is the finding, refused as :class:`ServedModelMismatchError`
with the code word :data:`SERVED_MODEL_MISMATCH_CODE`.  A caller that wants
the guarantee runs every completion through it before trusting the answer's
provenance.

Stdlib-only, like the rest of the member: this module reads an environment
mapping and constructs two backends, and touches no store and no network.  It
reads no credential at import — :data:`LIVE_PROVIDER_ENV_VARS` is names only,
and every value is read at :func:`live_provider` call time from the ``env``
handed in, which is ``os.environ`` by default.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

from ._anthropic import AnthropicProvider
from ._completion import Completion
from ._errors import ProviderError, ProviderNotConfiguredError
from ._live_http import Transport
from ._openai_compat import OpenAICompatProvider
from ._provider import Provider

__all__ = [
    "LIVE_PROVIDER_ENV_VARS",
    "SELF_HOSTED_API_KEY_ENV",
    "SELF_HOSTED_BASE_URL_ENV",
    "SERVED_MODEL_MISMATCH_CODE",
    "ServedModelMismatchError",
    "live_provider",
    "require_served",
]

#: The vendor spelling the Anthropic backend serves.  Called out as a name
#: because :func:`live_provider` branches on it and the vendor table below
#: omits it from the OpenAI-compatible set; a bare literal at each site would
#: leave a reader to notice the two are one fact.
_ANTHROPIC: Final[str] = "anthropic"

#: The self-hosted vendor's spelling, named for the same reason: two of the
#: environment lookups below branch on it — its base URL is required and its
#: key is optional — and a reader deserves to see that without counting.
_SELF_HOSTED: Final[str] = "self-hosted"

#: The environment variable holding the self-hosted base URL.  Required, and
#: the one vendor variable that names a *destination* rather than a
#: credential: the weights live wherever the operator runs them, so there is
#: no default for the vendor table to fall back on.
SELF_HOSTED_BASE_URL_ENV: Final[str] = "NULLIUS_SELF_HOSTED_BASE_URL"

#: The environment variable holding the self-hosted API key.  Optional — a lab
#: box behind no auth is a real deployment, not a misconfiguration — and an
#: absent or empty value means the provider sends no ``Authorization`` header
#: at all, which the OpenAI-compatible backend already reads an empty key as.
SELF_HOSTED_API_KEY_ENV: Final[str] = "NULLIUS_SELF_HOSTED_API_KEY"

#: One environment variable per vendor: the credential for the four hosted
#: vendors, and the base URL for the self-hosted one (whose credential is the
#: optional variable above, so this mapping stays "the variable a vendor
#: cannot be called without").  A frozen mapping built here rather than at
#: each call site, so the name a deployment exports and the name this module
#: reads are one edit and cannot drift.  Every name carries the ``NULLIUS_``
#: prefix that keeps research keys apart from claw-forge's own bare
#: ``ANTHROPIC_API_KEY``, which this module never reads.
LIVE_PROVIDER_ENV_VARS: Final[Mapping[str, str]] = MappingProxyType(
    {
        _ANTHROPIC: "NULLIUS_ANTHROPIC_API_KEY",
        "openai": "NULLIUS_OPENAI_API_KEY",
        "deepseek": "NULLIUS_DEEPSEEK_API_KEY",
        "google": "NULLIUS_GOOGLE_API_KEY",
        _SELF_HOSTED: SELF_HOSTED_BASE_URL_ENV,
    }
)

#: The vendors :class:`~providers._openai_compat.OpenAICompatProvider` serves,
#: derived from the table rather than re-spelled: every vendor the table knows
#: except the one the Anthropic backend covers.  Derived so a vendor added to
#: the table is served by :func:`live_provider` without a second edit.
_OPENAI_COMPAT_VENDORS: Final[frozenset[str]] = frozenset(
    vendor for vendor in LIVE_PROVIDER_ENV_VARS if vendor != _ANTHROPIC
)

#: The greppable word that opens every :class:`ServedModelMismatchError`
#: message: ``served_model_mismatch``.  An operator greps one token for *a
#: vendor quietly served a model other than the one the pin named* and lands
#: on this feature's one refusal — the §14.1 failure, made loud the moment
#: the answer arrives rather than discovered months later in an M3 paired
#: comparison whose two sides ran different models.  On the precedent
#: :data:`providers._budget.BUDGET_EXHAUSTED_CODE` sets for its own word.
SERVED_MODEL_MISMATCH_CODE: Final[str] = "served_model_mismatch"


class ServedModelMismatchError(ProviderError):
    """A completion was served by a model other than the one the pin named.

    Raised by :func:`require_served` when a completion's ``model`` is neither
    the pin's model nor the pin's model followed by ``-`` and the pin's
    version — the architecture §14.1 failure, where a vendor accepts a pinned
    id and serves another model (or snapshot) underneath it.  The message
    opens with
    :data:`SERVED_MODEL_MISMATCH_CODE` and names both sides (the model the pin
    asked for and the model that answered), so the operator reading it sees
    the finding itself rather than a paraphrase that dropped one of them.

    A :class:`~providers.ProviderError` directly, on the convention this
    package states for every new error class (every error class lives in the
    module that raises it and joins the interface's one base): a call that
    returned a completion from the wrong model completed the provider
    contract, but the *provenance* the pin exists to guarantee did not hold,
    and "the provider contract could not be completed as pinned" is exactly
    the question :class:`~providers.ProviderError` answers.
    """

    def __init__(self, message: str) -> None:
        # The code word is prefixed at the type rather than at the raise site,
        # so the token and the class are one edit and cannot drift apart — the
        # discipline every code word in this member follows.
        super().__init__(f"{SERVED_MODEL_MISMATCH_CODE}: {message}")

    @property
    def code(self) -> str:
        """The refusal's greppable code — :data:`SERVED_MODEL_MISMATCH_CODE`."""
        return SERVED_MODEL_MISMATCH_CODE


def _pin_parts(pin: object) -> tuple[str, str, str]:
    """Read ``(provider, model, version)`` off ``pin``, refusing anything else.

    A pin is recognised **structurally** — three string attributes — rather
    than by class, for the reason :func:`providers.require_agent_model_id`
    gives for the same choice: the workspace's module loader gives every
    member two class objects for one source file, so ``isinstance(pin,
    ModelPin)`` answers ``False`` for a pin the caller legitimately built from
    the member.  Reading the three parts is the recognition that survives
    that, and the parts are read on ``object.__getattribute__`` so an
    arbitrary object's ``__getattr__`` cannot fabricate a triple this function
    would then build a live provider from.

    The parts are not re-parsed through the triple's separator rules: they are
    read here to *dispatch on the vendor and name the wire model*, and a pin
    malformed enough to fail those rules is a configuration error this
    function cannot fix — it refuses a value that lacks the three parts
    outright, which is the shape a caller who passed the wrong object meets.
    """
    try:
        provider = object.__getattribute__(pin, "provider")
        model = object.__getattribute__(pin, "model")
        version = object.__getattribute__(pin, "version")
    except AttributeError:
        raise ProviderNotConfiguredError(
            f"a live provider is built from a pin — a provider/model/version "
            f"triple — and {pin!r} ({type(pin).__name__}) does not carry those "
            f"three parts. Construct the pin (providers.ModelPin) before "
            f"asking for its live provider; a value that names no vendor is "
            f"not a pin a backend can be chosen for."
        ) from None
    if not all(isinstance(part, str) and part for part in (provider, model, version)):
        raise ProviderNotConfiguredError(
            f"a pin's provider, model and version must each be a non-empty "
            f"string, got provider={provider!r}, model={model!r}, "
            f"version={version!r}. The vendor names the backend to build and "
            f"the model names the one it serves; a blank part is a pin that "
            f"cannot choose either, refused here before anything is built."
        )
    return provider, model, version


def _pin_effort(pin: object) -> str | None:
    """Read the ``effort`` a pin carries, or ``None`` when it names none.

    Read on ``object.__getattribute__``, the same defence :func:`_pin_parts`
    applies to the triple: an arbitrary object's ``__getattr__`` must not be
    able to fabricate an effort level for a pin that never stated one.  A
    plain :class:`~providers.ModelPin` has no such attribute at all and
    answers ``None`` here, exactly as it would for the triple's own optional
    facts — this is the one extra attribute :class:`~providers.AuthoringSession`
    attaches to the pin it hands its resolver, so the deployment's configured
    authoring effort reaches :class:`~providers._anthropic.AnthropicProvider`
    without widening this registry's ``pin -> Provider`` call shape.
    """
    try:
        effort = object.__getattribute__(pin, "effort")
    except AttributeError:
        return None
    return effort if isinstance(effort, str) else None


def _required_env(env: Mapping[str, str], name: str, vendor: str) -> str:
    """Read a variable a vendor cannot be called without, refusing if unset.

    An absent key and an empty value are one refusal because they are one
    deployment gap — *nothing to authenticate (or reach) the vendor with* —
    and both leave as :class:`~providers.ProviderNotConfiguredError` naming
    the variable.  The value is never rendered, not even when it is present
    and merely blank: the name is what an operator needs to set it, and a
    refusal is one of the three places a credential must never reach.
    """
    value = env.get(name)
    if not isinstance(value, str) or not value:
        raise ProviderNotConfiguredError(
            f"the live provider for vendor {vendor!r} needs {name} set in the "
            f"environment, and it is missing or empty. The variable is named "
            f"and its value is not rendered: a credential that appeared in an "
            f"exception message would have traveled into every bug report "
            f"that quoted one. Set {name} and build the provider again."
        )
    return value


def _optional_env(env: Mapping[str, str], name: str) -> str:
    """Read a variable that may honestly be absent, answering ``""`` if so.

    The self-hosted key's reader: a lab box behind no auth is a real
    deployment, so an absent or empty variable is answered with an empty
    string — which the OpenAI-compatible backend reads as "send no
    ``Authorization`` header at all" — rather than refused.
    """
    value = env.get(name)
    return value if isinstance(value, str) else ""


def live_provider(
    pin: object,
    env: Mapping[str, str] | None = None,
    transport: Transport | None = None,
) -> Provider:
    """Answer the live provider that serves ``pin``, credentials read from ``env``.

    The registry's one operation.  The pin's vendor decides the backend —
    :class:`~providers._anthropic.AnthropicProvider` for ``anthropic``, and
    :class:`~providers._openai_compat.OpenAICompatProvider` for ``openai``,
    ``deepseek``, ``google`` or ``self-hosted`` — and the vendor's own entry
    in :data:`LIVE_PROVIDER_ENV_VARS` names the variable its credential is
    read from.  The built backend is constructed for ``pin.model`` and that
    alone: the wire model is the pin's model, while the pin's version is
    provenance the caller checks after the answer with :func:`require_served`,
    never sends to the vendor.  For the ``anthropic`` vendor, an ``effort``
    attribute the pin carries (:func:`_pin_effort`; absent on a plain
    :class:`~providers.ModelPin`) is threaded into
    :class:`~providers._anthropic.AnthropicProvider` unchanged — the
    authoring session is the caller that attaches one.

    ``env`` defaults to :data:`os.environ` and is read at call time, so a
    caller — and every test — may hand a mapping of fake values and no real
    credential is touched; ``transport`` is passed straight through to the
    backend, so an injected transport answers from a script and opens no
    socket.  The ``NULLIUS_``-prefixed names are the only ones read: a bare
    ``ANTHROPIC_API_KEY`` in the environment is never consulted.

    A vendor with no backend, or a missing/empty required variable, raises
    :class:`~providers.ProviderNotConfiguredError` — a configuration the
    caller fixes, not a failure discovered mid-request — and the message names
    the variable or the vendor, never a credential's value.
    """
    provider_name, model, _version = _pin_parts(pin)
    environment: Mapping[str, str] = os.environ if env is None else env
    if provider_name == _ANTHROPIC:
        api_key = _required_env(
            environment, LIVE_PROVIDER_ENV_VARS[_ANTHROPIC], _ANTHROPIC
        )
        return AnthropicProvider(
            api_key, model=model, effort=_pin_effort(pin), transport=transport
        )
    if provider_name in _OPENAI_COMPAT_VENDORS:
        base_url: str | None = None
        if provider_name == _SELF_HOSTED:
            # The one vendor whose destination is configuration rather than a
            # default: the weights live wherever the operator runs them, so
            # the base URL is required and its own host becomes the
            # backend's allowlist (the operator naming the box *is* the
            # declaration the host guard exists to enforce).  Its key is the
            # optional variable, empty meaning "no Authorization header".
            base_url = _required_env(
                environment, SELF_HOSTED_BASE_URL_ENV, _SELF_HOSTED
            )
            api_key = _optional_env(environment, SELF_HOSTED_API_KEY_ENV)
        else:
            api_key = _required_env(
                environment, LIVE_PROVIDER_ENV_VARS[provider_name], provider_name
            )
        return OpenAICompatProvider(
            provider_name, api_key, model=model, base_url=base_url,
            transport=transport,
        )
    known = ", ".join(repr(vendor) for vendor in LIVE_PROVIDER_ENV_VARS)
    raise ProviderNotConfiguredError(
        f"vendor {provider_name!r} has no live backend; the vendors are "
        f"{known}. A pin's vendor must name one the live-providers addition "
        f"serves, and a vendor nobody has taught a backend for is a "
        f"configuration to fix here, before a call, rather than a request to "
        f"attempt."
    )


def require_served(pin: object, completion: Completion) -> Completion:
    """Answer ``completion`` unchanged, or refuse a completion served by another model.

    The check architecture §14.1 exists for.  The completion's ``model`` — the
    model that actually served the answer, copied verbatim from the vendor by
    the backend — must be either ``pin.model`` exactly, or ``pin.model``
    followed by ``-`` and ``pin.version`` (the exact dated snapshot the pin
    names).  Either is admitted, and the completion is answered *unchanged* —
    this is a check, not a translation, so nothing about the answer is
    rebuilt or normalized.  Anything else is a vendor serving a model (or
    snapshot) the pin never named, and leaves as
    :class:`ServedModelMismatchError`.

    The matching is exact in both directions: an exact name and *the pinned*
    dated snapshot are the only two admitted spellings, so
    ``deepseek-v4-flash`` pinned to version ``20260401`` serves
    ``deepseek-v4-flash-20260401``; a different date, a vendor-invented suffix
    such as ``-preview``, an empty suffix, a case variant, or a different name
    entirely — ``deepseek-v4.1-flash``, ``deepseek-chat`` — is the §14.1 swap
    and is refused, because the whole point is that any model or snapshot
    other than the one pinned must be told apart rather than folded together.
    """
    provider_name, model, version = _pin_parts(pin)
    served = getattr(completion, "model", None)
    if not isinstance(served, str) or not served:
        raise ServedModelMismatchError(
            f"a completion served by the pin {provider_name}/{model}/{version} "
            f"must name the model that served it, and this one carries "
            f"{served!r} ({type(completion).__name__}). The serving model is "
            f"the whole evidence this check reads; a completion that does not "
            f"name one cannot be shown to have been served by the pinned "
            f"model, and is refused rather than assumed to have been."
        )
    if served == model or served == f"{model}-{version}":
        return completion
    raise ServedModelMismatchError(
        f"the pin {provider_name}/{model}/{version} asked for model {model!r}, "
        f"and the vendor served {served!r}. A serving model equal to the "
        f"pinned model, or the pinned model followed by '-' and the pinned "
        f"version ({model}-{version}), is the pinned snapshot and is admitted; "
        f"{served!r} is neither, which is a vendor quietly serving another "
        f"model or a different snapshot of it — the architecture §14.1 "
        f"failure, where a retired id keeps being accepted under a different "
        f"model. This answer's provenance is not the pinned model's, and it is "
        f"refused rather than recorded as one."
    )
