"""The pinned authoring model — feature 203's triple, and the alias it refuses.

app_spec.xml, "LLM Provider Tiering & Agent Pinning", feature 203: *System
persists ``agent_model_id`` per node as a provider, model and version triple
rather than a rolling alias.*  Feature 192 gives the deployment one seam every
model call passes through; this module gives every **node** the identity of the
model that authored it, in the shape the tree store's column can hold and the
shape a stratification can group by.

Why a triple, and not a string
------------------------------

The column is ``node.agent_model_id TEXT NOT NULL`` — one string — and
``TEXT NOT NULL`` will happily accept ``'deepseek-flash'``.  That is the §14.1
failure exactly.  docs/nullius-tech-architecture.md §14.1 records it as history
rather than hypothesis:

    **This is not hypothetical.** In September 2026 DeepSeek retired
    ``deepseek-v4-flash`` while continuing to accept the ID, silently serving
    V4.1-Flash instead. A campaign run in August and one in September under the
    same model string were generated by **different models**. ... the world
    pool becomes heterogeneous in an uncontrolled variable, and that variable
    sits inside the M3 paired comparison.

A node stamped ``'deepseek-flash'`` therefore belongs to no model stratum: the
string names a *target* the provider may re-point at will, not a model that
served.  The spec's answer is a triple — provider, model, version — because
each part answers a different question and only all three together name one
thing:

* ``provider`` — *whose* service served it.  Two providers offering the same
  open weights are two supply chains, two rate limits and two failure modes,
  and §14.1's root rotation (feature 197) proposes across exactly this axis.
* ``model`` — which model of that provider's line.  ``deepseek-flash`` and
  ``deepseek-chat`` are different models of one provider, and the same name
  under two providers can be two different things.
* ``version`` — which snapshot of it.  This is the part that stops a rolling
  alias: ``V4.1`` is a date-stamped-or-dateless *identity*, and architecture
  §14.1 mitigation 2 states the preference — *"Prefer dateless IDs that are
  documented as pinned snapshots rather than rolling aliases, where the
  provider offers that guarantee."*

**No part is required to look like a date.**  It is tempting to demand ISO
dates of ``version``, and it would be wrong: mitigation 2's own recommendation
is ``claude-opus-5`` — a dateless id the provider documents as a pinned
snapshot, and the id §14.1's root tier actually names.  A date check would
refuse the very ids the architecture recommends.  What feature 203 can enforce
without a provider's documentation is *structure*: three parts, each non-empty,
and therefore a value a model stratum can be keyed on.  Whether a given version
string is genuinely immutable is a procurement fact, not a parseable one, and
this module says so rather than pretending a regex can decide it.

The rendering, and the one separator
------------------------------------

The triple is stored as its three parts joined by :data:`SEPARATOR` —
``"anthropic/claude-opus-5/20260401"`` — which is the conventional
``provider/model/version`` spelling PRD §4's provenance block and architecture
§9.1's column comment both write (``-- provider/model/version``).  The
separator is fixed and the parts may not contain it, so the rendering is
*injective*: one string, one triple, and therefore one stratum per stored
value.  Without that rule ``("a/b", "c", "d")`` and ``("a", "b/c", "d")`` would
render alike and two different models would share a stratum — the same class of
silent conflation the triple exists to end.

The inverse (:func:`require_agent_model_id`) is strict, and strictness is the
feature: a value that is not three separator-joined non-empty parts is refused
as a :class:`~providers.RollingAliasError`, never guessed at, never padded with
a default part.  A reader that "recovered" a triple from ``'deepseek-flash'``
by inventing a provider or a version would manufacture precisely the false
stratum the refusal exists to prevent.

The value type
--------------

:class:`ModelPin` is a frozen, value-equal dataclass for the reasons the rest
of this package's records are (see :mod:`providers._completion`): it is a fact
about the past — which model wrote this node — and a fact is not something a
caller mutates.  Equality is by value, so ``pin == ModelPin.parse(stored)`` is
the store's idempotence check and a suite can assert on the triple directly
rather than on a string.

Stdlib-only: this module holds three strings and the rule that joins them; it
touches no store and imports nothing outside the standard library.  The store
that writes the column is :mod:`providers._pin_store`.
"""

from __future__ import annotations

from dataclasses import dataclass

from ._pin_errors import RollingAliasError

__all__ = [
    "AGENT_MODEL_ID_COLUMN",
    "MODEL_PIN_PARTS",
    "MODEL_PIN_REVISION",
    "NODE_TABLE",
    "SEPARATOR",
    "ModelPin",
    "require_agent_model_id",
]

#: The separator the triple renders with — the one character a part may not
#: contain.  ``provider/model/version`` is the spelling PRD §4's provenance
#: block and architecture §9.1's column comment both write; fixing it here (and
#: refusing it inside a part) is what makes the rendering injective, so one
#: stored string names exactly one model.
SEPARATOR = "/"

#: The three parts, in the order they render and in the order feature 203 names
#: them.  Declared as data because more than the rendering iterates it — the
#: refusal below builds its message from it, and the suite pins the *order* by
#: it, so "provider, model and version" cannot quietly become
#: "provider, version and model" and re-key every stratum in the store.
MODEL_PIN_PARTS: tuple[str, ...] = ("provider", "model", "version")

#: The ``node`` column the triple is persisted into — feature 100's, spelled by
#: the spec's own schema block and created by revision ``0115``.  Named here
#: rather than restated at each call site so the store, the refusal and the
#: suite share one string.
AGENT_MODEL_ID_COLUMN = "agent_model_id"

#: The table that column lives on — feature 97's, created by revision ``0118``.
NODE_TABLE = "node"

#: The revision that adds the column — feature 100's migration.  Named as data
#: because it is the whole actionable content of a
#: :class:`~providers.PinColumnError`: a store pointed at a database that has
#: not reached this revision has no column for a pin to live in, and the repair
#: is to run the chain to here.
MODEL_PIN_REVISION = "0115_agent_model_trio"


def _require_part(value: object, part: str) -> str:
    """Return ``value`` as one clean part of a triple, refusing anything else.

    Three refusals, one message form, because they are one rule: *a part of a
    triple is a non-empty, separator-free string that is its own canonical
    form.*  All of them leave as
    :class:`~providers.RollingAliasError` — the seam's vocabulary is this
    feature's, never the standard library's ``TypeError`` or ``ValueError``, so
    a caller that catches the feature's refusal gets the same answer however it
    malformed the triple.

    The canonical-form clause is the quiet one and it is load-bearing.  A part
    carrying leading or trailing whitespace would render to a stored string
    that does not round-trip — ``"anthropic / claude-opus-5 / v1"`` parses back
    to parts with spaces, which compare unequal to the parts that were written
    — so a retry of the identical pin would read as a *different* model and be
    refused as a conflict.  Stripping the caller's value instead would be the
    other wrong answer: it would let two spellings of one model be stored, and
    the stratum key is the stored string.  So the whitespace is refused, and
    the caller is told to pass the canonical form.
    """
    if not isinstance(value, str):
        raise RollingAliasError(
            f"a model pin's {part} must be a string, got {value!r} "
            f"({type(value).__name__}). Feature 203 pins a node's authoring "
            f"model as a {SEPARATOR.join(MODEL_PIN_PARTS)} triple, and each "
            f"part of that triple is a name — a non-string is not a name any "
            f"stratum can be keyed on."
        )
    if not value:
        raise RollingAliasError(
            f"a model pin's {part} must be a non-empty string. A triple with an "
            f"empty {part} names no {part} — {value!r} rendered with its "
            f"siblings would read as a model that has one, and the stratum it "
            f"produced would be a stratum of a model that does not exist."
        )
    if value != value.strip():
        raise RollingAliasError(
            f"a model pin's {part} must be its own canonical form, got "
            f"{value!r}, which carries surrounding whitespace. The stored "
            f"agent_model_id is the triple rendered as text, so a part with "
            f"padding would not round-trip: re-reading the stored value would "
            f"yield a different {part} than the one written, and a retry of the "
            f"identical pin would be refused as a conflict with itself. Pass "
            f"{value.strip()!r} if that is the model you mean."
        )
    if SEPARATOR in value:
        raise RollingAliasError(
            f"a model pin's {part} must not contain {SEPARATOR!r}, got {value!r}. "
            f"The triple renders as provider{SEPARATOR}model{SEPARATOR}version, "
            f"so a part carrying the separator would make the rendering "
            f"ambiguous — two different triples would produce one stored "
            f"string, and two different models would share a stratum, which is "
            f"the conflation feature 203 exists to end."
        )
    return value


@dataclass(frozen=True)
class ModelPin:
    """One node's authoring model, as a provider, model and version triple.

    Feature 203's value type.  The three parts are the three questions that
    together name one model — *whose service*, *which model of its line*, *which
    snapshot of it* — and each is validated on construction, so a ``ModelPin``
    that exists is a triple the store can render, a stratification can group by
    and a reader can invert.

    Frozen and value-equal: it is a fact about which model wrote a node, and an
    author is history rather than a field.  Equality is by value, which is what
    makes the store's idempotence check a comparison of pins rather than of
    strings — two pins built from different objects but the same three names
    are the same model, and a retry carrying one is answered rather than
    refused.
    """

    provider: str
    model: str
    version: str

    def __post_init__(self) -> None:
        # Validated part by part, in the order the triple renders, so a pin
        # malformed in two places is refused for the first one a reader would
        # meet — the same ordering :class:`~providers.Completion` uses to
        # decide which field a malformed answer fails on.
        object.__setattr__(self, "provider", _require_part(self.provider, "provider"))
        object.__setattr__(self, "model", _require_part(self.model, "model"))
        object.__setattr__(self, "version", _require_part(self.version, "version"))

    @classmethod
    def parse(cls, value: object) -> ModelPin:
        """Read a stored ``agent_model_id`` back into the triple it names.

        The classmethod spelling of :func:`require_agent_model_id`, for a
        caller that holds the value type rather than the free function.  It
        delegates rather than re-implementing: there is one parse of the
        stored form in this package, so the write path and the read path cannot
        disagree about what ``'a/b/c'`` means.
        """
        return require_agent_model_id(value)

    @property
    def agent_model_id(self) -> str:
        """The triple as the ``node.agent_model_id`` column stores it.

        ``provider/model/version``, the spelling the column's own comment in
        architecture §9.1 writes.  A property rather than ``__str__`` alone, so
        the value a store writes is named by the column it goes into, and a
        caller rendering a pin for a log line reaches for ``str(pin)`` instead
        — the two agree by construction because both come from
        :meth:`__str__`.
        """
        return str(self)

    def __str__(self) -> str:
        return SEPARATOR.join((self.provider, self.model, self.version))


def _pin_parts_or_none(value: object) -> tuple[str, str, str] | None:
    """The three parts of ``value`` if it is a pin, else ``None``.

    A pin is recognised structurally — three string attributes named by
    :data:`MODEL_PIN_PARTS` — rather than by class, because the workspace's
    module loader gives every member two class objects for one source file (see
    :func:`require_agent_model_id`).  Checked on ``object.__getattribute__``
    rather than ``getattr`` so an arbitrary object's ``__getattr__`` cannot
    fabricate a triple: this function is the gate that decides what may be
    stored in a node's ``agent_model_id``, and a hook that answered three
    strings would be a hook that pinned a model.

    The parts are not re-validated here.  They were validated when the pin was
    constructed — that is what constructing one *is* — so this is a
    recognition, not a second check with its own rules to drift from.
    """
    try:
        parts = tuple(
            object.__getattribute__(value, part) for part in MODEL_PIN_PARTS
        )
    except AttributeError:
        return None
    if not all(isinstance(part, str) for part in parts):
        return None
    return parts  # type: ignore[return-value]


def require_agent_model_id(value: object) -> ModelPin:
    """Return ``value`` as a :class:`ModelPin`, refusing a rolling alias.

    The one parse of the stored form, and the feature's gate: a value that is
    three separator-joined non-empty parts *is* a pinned triple, and anything
    else is a rolling alias — refused as
    :class:`~providers.RollingAliasError` with the value in the message.

    The refusal is deliberately unaccommodating, in both directions a caller
    meets it:

    * A **one-part** value (``'deepseek-flash'``, ``'claude-opus-5'``) is the
      announcement case §14.1 documents — a model id whose meaning is the
      provider's to change.  The refusal says so, because the caller's next
      question is *why can't I store what the API gave me?* and the answer is
      that the API's id is not a promise.
    * A **two-part** value (``'deepseek/flash'``) is worse, not better: it
      names a model line without the snapshot, which is a re-routing target
      with the re-routing written down.  Refused on the same grounds.
    * A **four-part** value is refused rather than truncated, because guessing
      which of the extra parts is the version would be inventing a stratum.

    The parts are parsed positionally — provider, then model, then version —
    because that is the order :data:`MODEL_PIN_PARTS` declares, and the order
    the spec and the architecture's column comment both write it in.

    A pin is recognised by its **parts, not its class**, and that is not a
    stylistic preference — it is load-bearing in this workspace.  The module
    loader imports every member *twice*: once by file path under
    ``_nullius_scanned_<dir>`` and once as the importable member, so
    ``providers.ModelPin`` and the scanned package's ``ModelPin`` are two
    distinct classes over one source file.  A
    ``isinstance(value, ModelPin)`` check therefore answers *False* for a pin
    the caller legitimately built from the member — and worse than answering
    wrong, it would land in the not-a-string branch below and tell that caller
    they "have not pinned a model at all" about the very type this feature
    defines.  The checked shape is what actually matters here: anything
    carrying the three parts *is* the answer, whichever module object it came
    from.  The same duck-typing the ported-world adapter (feature 190) uses at
    its seam, for the same reason.

    **A recognised pin is re-made from its parts rather than passed through**,
    and that is the second half of the same problem.  ``ModelPin`` is a
    dataclass, so its generated ``__eq__`` returns ``False`` between two
    classes even when every field matches — which means a pin from the scanned
    copy would compare unequal to one built here, and the store would answer
    *"already records X, and this call pins X"*: a conflict whose two sides are
    the same string.  Returning a pin built from *this* module's class means
    everything downstream — the equality check, :attr:`ModelPin.pin` on the
    answer record, the value a caller gets back — is one class, and the seam
    has normalized in the sense its name promises.  The cost is three string
    copies on a path that already renders the triple.
    """
    parts = _pin_parts_or_none(value)
    if parts is not None:
        # Re-made from the parts, not returned as handed: see above — the
        # caller's class may be the other copy, and equality across the two is
        # False for every value.
        return ModelPin(provider=parts[0], model=parts[1], version=parts[2])
    if not isinstance(value, str):
        raise RollingAliasError(
            f"an agent_model_id must be a string, got {value!r} "
            f"({type(value).__name__}). Feature 203 persists a node's "
            f"authoring model as the {SEPARATOR.join(MODEL_PIN_PARTS)} triple "
            f"rendered as text; anything else is not a value the column can "
            f"hold, and a caller that passes one has not pinned a model at all."
        )
    parts = value.split(SEPARATOR)
    if len(parts) != len(MODEL_PIN_PARTS):
        raise RollingAliasError(
            f"an agent_model_id must be a "
            f"{SEPARATOR.join(MODEL_PIN_PARTS)} triple, got {value!r} — "
            f"{len(parts)} part{'s' if len(parts) != 1 else ''} rather than "
            f"{len(MODEL_PIN_PARTS)}. A provider alias re-routes silently "
            f"(architecture §14.1: DeepSeek retired deepseek-v4-flash on "
            f"2026-09-10 while continuing to accept the id, serving V4.1-Flash "
            f"underneath it), so a node stamped with one belongs to no model "
            f"stratum and the value cannot be recovered by guessing which part "
            f"is missing — the stratum it invented would be a stratum of a "
            f"model that never ran."
        )
    # The parts are validated by the record's own guard, in the record's own
    # order: constructing the pin *is* the check, so a value malformed in a
    # part (empty, padded, or carrying the separator twice in a way that split
    # into three anyway) is refused by the same rule that guards a pin built
    # from three arguments.  There is no second validation path to drift.
    return ModelPin(provider=parts[0], model=parts[1], version=parts[2])
