"""System rejects the merge when a node record carries no agent_model_id
value.

app_spec.xml feature 358 — the "System Invariant CI Gates" category's
node-record gate — is the merge-time form of a law the spec states at
run time twice, once per member that writes the column. PRD §13, item 5a
among the invariants that *"violating any of these silently invalidates
the system"*: *"Every node records ``agent_model_id``. Provider aliases
re-route silently; a pinned snapshot or a self-hosted checkpoint hash is
the only real guarantee. M3 results are reported per model stratum as
well as pooled."* §13's preamble names this gate's venue: *"Enforce in
CI, not in code review."* The architecture states the column the law
reads in two places — §9.1's table spells ``agent_model_id TEXT NOT
NULL`` with the comment ``-- provider/model/version — see §14.1``, and
§14.1's provenance section states why the column is ``NOT NULL`` at all:
``evaluator_hash``, ``snapshot_hash`` and ``cost_model_hash`` *"pin
everything except the thing that wrote the code"*, and the thing that
wrote the code is what this column records. Migration 0115 — feature
100's, the column's creator — draws the two halves of this gate in one
sentence: *"the write path refuses what the column cannot represent, and
the column's constraint says the same thing ahead of the write."*

**The subject is the node record a merge's write path authors, read as
data — in the three places a merge carries it.** First the **column**:
0115 returns its DDL as inspectable data, and the ``ALTER TABLE`` that
adds ``agent_model_id`` spells ``NOT NULL`` on both dialects with no
``DEFAULT`` anywhere — 0115's own argument for the absence: *"``DEFAULT
'unknown'`` fabricates one"* stratum, and a default would have to be
true of every row that predates the column, which no value is. Second
the **record**: the orchestrator's node row is written from
:class:`discovery.AttemptProvenance` — feature 240's deployment-supplied
half, the frozen value whose ``agent_model_id`` lands in every node row
the tree holds — and the field is *required*, with no default a caller
could omit silently, because the module's own stance is that the
authoring trio is *"the deployment's record of the world the attempt ran
in"* and *"a module that defaulted any of them would be fabricating
provenance"*. Third the **pin**: :func:`providers.require_agent_model_id`
is feature 203's one parse of the stored form, and the store that stamps
the column (:class:`providers.AgentModelPins`) refuses a valueless pin
*before it opens the database* — the refusal is a fact about the record,
reached without touching the tree.

**The no-value spellings fold, because the record is data and every
spelling of nothing is nothing.** The absent key — a record whose writer
never named the column. ``None`` — SQL NULL, the state 0115's
``NOT NULL`` could not cover on a populated table and feature 203's
backfill writes out of. The empty string — the spelling 0115 itself
names for this feature: *"an empty string is exactly what feature 358's
no-value check reads as absent."* Whitespace — the realistic half, the
spelling that passes a bare ``IS NULL`` test and lands in a stratum no
model answers to (the reason the stratification read spells ``TRIM``
explicitly). And the non-string — no value the ``TEXT`` column holds, in
feature 203's own words *"a caller that passes one has not pinned a
model at all."* The evaluator below folds all five into one boolean, the
way the runtime faces do; a gate that enumerated spellings by grep would
miss the sixth.

**The refusal lands before the row exists, at every face.** The record
refuses at construction — a provenance that carries no model value
cannot be built, so there is no attempt to log and no row to write; the
member's own vocabulary (:class:`discovery.AttemptLogError`) names the
column and the constraint, so the operator reads the finding off the
exception. The pin seam refuses in
:class:`providers.RollingAliasError`, feature 203's class, at both the
free function and the store's write. And the column itself refuses the
``INSERT`` on a table the chain built — pinned below on an in-memory
database, the way the promotion gate runs its two engines — which is the
belt behind the belt: even a caller that bypassed every record surface
would meet the constraint the DDL declares.

**Why CI, and why the harm is silent.** A node with no model string is
*a node the stratification cannot place* — 0115's own words — and the
stratification is the whole point of the column: feature 100 adds it *"so
a pool can be stratified by authoring model"*, §14.1's third mitigation
says *"record and stratify"*, and M3 reports per model stratum as well
as pooled. §14.1 documents what an unstratifiable pool costs: a campaign
run in August and one in September *"under the same model string were
generated by **different models**"*, and *"that variable sits inside the
M3 paired comparison."* A node carrying no value at all is worse than
one carrying an alias — the alias at least names a target — and the
runtime readers refuse rather than bucket it, in feature 215's words
because *"a diversity figure that quietly shrank would flatter exactly
the model whose nodes went missing"* and a stratum labelled ``unknown``
would *"be a value a report would print beside the real models as though
it were one of them."* Those refusals ship in merges too, so this gate
holds them as data: the shipped stratification read refuses both
spellings the writer cannot produce. And the gate's own judgement needs
no database — the evaluators are pure functions of stated data, pinned
statically below, because a gate that had to run a write to judge it
would be an audit after the fact.

**What this gate is not, asserted as hard as what it is.** It is not
feature 203's rolling-alias refusal: ``'deepseek-flash'`` *is* a value —
a one-part name of a target — and this gate does not refuse it; the pin
seam refuses it under 203's own sentence, and the two sentences divide
the labour exactly, this one refusing the *absence* and that one
refusing the *alias*. It is not a judgement on the trio's other columns:
``agent_ckpt_hash`` is nullable by §9.1's own annotation (*"non-null for
self-hosted weights"* — its ``NULL`` records hosted-API weights, a
positive fact), and ``agent_sampling`` defaults honestly because the
dice are known at authoring time even when they are defaults; the model
is the one member of the trio with no honest default, which is why the
field is required and the column is ``NOT NULL``. It is not the proposal
history's deliberate absence: the signal agent's ``node_proposal`` table
carries no copy of the column by design — *"a reader that wants it
joins"* — and a gate that greped every record for the column name would
refuse that legal design. It is not the chain-ordering subject: a
database that has not reached 0115 has no column at all, a different
refusal the stratification features already raise in their own
vocabulary. And it is not the member suites' own write-path tests —
those pin the ``INSERT`` and the idempotent refresh from inside; this
gate reads what a merge carries, from outside it, and adds the face no
writer-side test can promise: a record surface that *accepts* a
no-value spelling refuses the merge whatever else it does.

**No dialect.** The column's declaration is dialect-invariant —
``TEXT`` and ``NOT NULL`` on Postgres and SQLite alike, the one pair in
the trio with no split (the ``JSONB`` translation belongs to the
sampling sibling) — and the record and the pin are Python values with no
second spelling for a database to disagree about. The one restatement
that exists — the composed application carries the pin store under one
registered name, resolving ``DATABASE_URL`` at build time — is pinned
below exactly as it ships, on the plain-data fields the dual module
worlds can compare.
"""

from __future__ import annotations

import ast
import dataclasses
import hashlib
import importlib.util
import inspect
import sqlite3
from collections.abc import Callable, Mapping
from contextlib import closing
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
from discovery import Attempt, AttemptLogError, AttemptProvenance
from providers import (
    AgentModelPins,
    ModelPin,
    RollingAliasError,
    build_agent_model_pins,
    require_agent_model_id,
)

# The read-side belt and the joining history, read where they live.  A store
# has no public ``statements()`` seam the way a migration does — these private
# constants ARE the shipped SQL — and they are the merge-carried artifacts the
# belt face and the scope face below judge.  Restating their SQL in this file
# would let the gate agree with itself and pass anything, the same failure
# mode a re-typed DDL would give the ledger gate.
from signal_agent._diversity import _UNMODELLED_SQL
from signal_agent._proposal import _SCHEMA as _PROPOSAL_SCHEMA

from app.module_loader import registered_components

# ── The column's owner, loaded the way its runner loads it ────────────────────

#: tests/invariants/test_node_agent_model_id_value.py → tests/invariants →
#: tests → the repository root, whose migrations/ tree holds the DDL this
#: gate judges.
REPO_ROOT = Path(__file__).resolve().parents[2]

#: The migration tree's versions directory — the one place a merge's DDL
#: lives. The gate reads it rather than a restatement, so DDL edited in a
#: candidate merge is judged as it will ship, not as this file remembers it.
VERSIONS_DIR = REPO_ROOT / "migrations" / "versions"

#: The revision that owns the column: 0115 is feature 100's migration — the
#: ``ALTER TABLE`` that adds the authoring-model trio and spells this gate's
#: column ``NOT NULL`` on both dialects.
TRIO_REVISION = "0115_agent_model_trio"


def _load_migration(revision: str) -> ModuleType:
    """Load ``revision`` from the versions directory, by path.

    ``migrations/`` is not a package and is not on ``sys.path``; a runner
    loads a migration by path the same way, so loading it by path here is
    the shape a migration is *built* to be used in rather than a
    workaround. A missing file fails with the path in the message, because
    the one failure a gate should never have to guess at is "the column's
    owner moved" — a gate that silently skipped the DDL would pass for a
    merge that shipped anything.
    """
    path = VERSIONS_DIR / f"{revision}.py"
    if not path.is_file():
        raise AssertionError(
            f"{revision} is not at {path}; this gate judges the migration "
            "that owns node.agent_model_id, so it needs the column's owner "
            "to be where the tree keeps it"
        )
    spec = importlib.util.spec_from_file_location(f"_invariants_{revision}", path)
    assert spec is not None and spec.loader is not None, path
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


#: The migration that owns the column, loaded once at collection — reading
#: it is a precondition of every judgement below, not a behaviour any one
#: test chooses.
MIGRATION = _load_migration(TRIO_REVISION)

# ── The law's own spellings, restated as data ────────────────────────────────

#: The one column this gate is scoped to, in the spelling the spec's schema
#: block, §9.1's table and §13 item 5a all write — restated as data rather
#: than imported, so the gate pins *that* column rather than agreeing with
#: whatever name a member's constant carries today.
NODE_RECORD_COLUMN = "agent_model_id"

#: The component name the providers member registers its pin store under —
#: the one name a composed application knows the column's writer by,
#: restated as data for the same reason.
AGENT_MODEL_PINS_COMPONENT = "agent-model-pins"

#: The stands value: §14.1's own model, as the triple feature 203 spells it
#: — the provider whose September re-route the architecture documents, the
#: model it retired, and the August snapshot a campaign was genuinely
#: authored under. One string that names exactly one model, so every stands
#: case below is non-vacuous, and the pin seam's parse of it cross-checks
#: the restatement against the member's own rendering.
GATE_TRIPLE_PARTS: tuple[str, str, str] = (
    "deepseek",
    "deepseek-v4-flash",
    "2026-08-01",
)
GATE_TRIPLE = "/".join(GATE_TRIPLE_PARTS)

#: The stands record's provenance triple — three 64-hex digests, the shape
#: ``AttemptProvenance`` validates, none of them this gate's subject.
GATE_EVALUATOR_HASH = "ab" * 32
GATE_SNAPSHOT_HASH = "cd" * 32
GATE_COST_MODEL_HASH = "ef" * 32

#: The gate's tree identities: one parent whose attempt is logged, the
#: campaign it belongs to, and a second node for the store face — patterned
#: UUIDs, the spelling every column the tree keys on canonicalizes to.
GATE_PARENT = "11111111-1111-4111-8111-111111111111"
GATE_CAMPAIGN = "22222222-2222-4222-8222-222222222222"
GATE_OTHER_NODE = "33333333-3333-4333-8333-333333333333"

#: The attempt the stands record logs: real source text, its true sha256,
#: and a theme from the legal vocabulary — so the row below is a row the
#: member's own validation accepts, not a fixture shaped around the gate.
GATE_THEME_ROOT = "term-structure carry"
GATE_CODE = "def signal(rows):\n    return tuple(0.0 for _ in rows)\n"
GATE_CODE_HASH = hashlib.sha256(GATE_CODE.encode("utf-8")).hexdigest()
GATE_ARTIFACT_URI = "file:///lake/staging/gate/node/"

#: The sentinel for the one spelling no argument can carry: a record whose
#: writer never named the column at all. Absence is a property of the
#: rendered record, so it is judged by the row face, never passed as a
#: value.
MISSING: Any = object()

#: The no-value spellings the gate refuses, in the order the law's own
#: words suggest them. A spelling counts as refused when asking a shipped
#: surface to carry it raises; the per-spelling faces below pin the classes
#: the shipped refusals carry, which is what keeps this aggregate's breadth
#: anchored rather than excused.
NO_VALUE_SPELLINGS: tuple[tuple[str, Any], ...] = (
    (
        "agent_model_id absent from the record — the column no writer names",
        MISSING,
    ),
    (
        "agent_model_id=None — SQL NULL, the state the backfill writes out of",
        None,
    ),
    (
        "agent_model_id='' — the empty string, a value that names no model",
        "",
    ),
    (
        "agent_model_id='   ' — whitespace, the spelling a bare IS NULL passes",
        "   ",
    ),
    (
        "agent_model_id=17 — a non-string, no value the TEXT column holds",
        17,
    ),
)

#: The spellings a carried-value surface can be asked for — every one above
#: except the absent key, which no callable can be handed. These are what
#: ``merge_refusal`` asks of each surface, and what the witness accepts all
#: of when the gate demonstrates its own discrimination.
CARRIED_SPELLINGS: tuple[tuple[str, Any], ...] = tuple(
    (description, value)
    for description, value in NO_VALUE_SPELLINGS
    if value is not MISSING
)

#: Each carried spelling keyed by its value, so the row face can name the
#: spelling a rendered record carries rather than saying merely "refused".
#: Every value in the table is hashable and unique; the absent key is the
#: sentinel itself.
_SPELLING_OF: dict[Any, str] = {
    value: description for description, value in NO_VALUE_SPELLINGS
}


# ── The stands record the gate renders ───────────────────────────────────────


def gate_provenance(agent_model_id: Any = GATE_TRIPLE) -> AttemptProvenance:
    """One deployment record of the world an attempt ran in.

    The provenance half of every node row the orchestrator writes, with the
    authoring model as the one parameter — the surface ``merge_refusal``
    asks each spelling of. The default is the stands triple, so the gate's
    own fixture data carries a value and every judgement below that builds
    a record without naming the column is judging the stands case, not
    silently exercising an absence.
    """
    return AttemptProvenance(
        evaluator_hash=GATE_EVALUATOR_HASH,
        snapshot_hash=GATE_SNAPSHOT_HASH,
        cost_model_hash=GATE_COST_MODEL_HASH,
        agent_model_id=agent_model_id,
    )


def gate_attempt(provenance: AttemptProvenance) -> Attempt:
    """One attempt as feature 240 logs it — the record the row renders from.

    Built the member's own way (real code, its true hash, a legal theme, a
    parent and a campaign) so the row it renders is a row the write path
    would actually write, and the gate's judgement of that row is a
    judgement of the shipped shape rather than of a fixture invented to
    pass it.
    """
    return Attempt(
        parent_id=GATE_PARENT,
        campaign_id=GATE_CAMPAIGN,
        theme_root=GATE_THEME_ROOT,
        depth=1,
        code=GATE_CODE,
        code_hash=GATE_CODE_HASH,
        stated_mechanism=None,
        provenance=provenance,
    )


def _chain_built_node_table() -> sqlite3.Connection:
    """A ``node`` table as the assembled chain builds it, in memory.

    The skeleton 0118 creates plus 0115's own ``upgrade`` — the columns the
    chain a merge ships would add, applied by the migration's own code
    rather than by DDL retyped here, so the constraint the belt below
    exercises is the constraint the merge declares.
    """
    connection = sqlite3.connect(":memory:")
    connection.execute(f"CREATE TABLE {MIGRATION.NODE_TABLE} (id TEXT PRIMARY KEY)")
    MIGRATION.upgrade(connection)
    return connection


# ── The finding's witness ────────────────────────────────────────────────────


class UnpinnedRecord:
    """A node record that carries no agent_model_id value — the finding itself.

    Nothing the shipped surfaces accept can carry the finding: the record's
    field is required and validated, the pin seam refuses every valueless
    spelling, and the column refuses the insert. So a record that carries
    no value arrived past them — a backfill, a vendor writer, a hand-rolled
    row a caller handed the tree — and this class is that hand. It builds
    the two quiet drifts a merge could ship: a field *defaulted* to ``None``
    (construction never refuses) and a row that *omits the key* when the
    value is ``None`` (the column no writer names). Both are the sentence's
    subject stated as code, and the gate names every spelling each one
    accepts.
    """

    def __init__(self, *, agent_model_id: Any = None) -> None:
        self._agent_model_id = agent_model_id

    def row(self) -> dict[str, Any]:
        """The node record the witness renders — the column conditionally
        present, which is the absence wearing a writer's shape."""
        row: dict[str, Any] = {"id": GATE_PARENT, "code_hash": GATE_CODE_HASH}
        if self._agent_model_id is not None:
            row[NODE_RECORD_COLUMN] = self._agent_model_id
        return row


# ── The evaluators: the finding as a pure function of stated data ────────────


def no_model_value(value: Any) -> bool:
    """Whether a node record's agent_model_id spelling carries no value.

    The finding the sentence refuses, evaluated over the one thing every
    seam reads: the value a record states for the column. Every spelling
    the runtime faces refuse folds in here — the absent key (passed as the
    sentinel), SQL ``NULL``, the empty string 0115 names for this feature,
    whitespace that a bare ``IS NULL`` test would pass, and any non-string,
    which is no value the ``TEXT`` column holds and no stratum a report
    could print. A string that strips non-empty is a value whatever it
    names — whether it names a model *truthfully* is feature 203's
    question, not this one's.
    """
    if value is MISSING or value is None:
        return True
    if not isinstance(value, str):
        return True
    return not value.strip()


def merge_refusal(carry: Callable[..., Any]) -> tuple[str, ...]:
    """The gate itself: the no-value spellings a record surface accepts.

    Asks a node-record authoring surface — any callable that takes the
    column as a keyword, which is the shape of both shipped surfaces (the
    provenance record's construction and the pin seam's parse) — to carry
    each no-value spelling in turn, and names the spellings it accepted.
    Empty means the merge stands: every no-value spelling was refused by
    the surface it was asked of. Computed by asking, never by writing, so
    the gate cannot author a row while judging the record that would
    produce one.

    A spelling counts as refused when asking for it raises; the
    per-spelling faces below pin the exact classes the shipped refusals
    carry, which is what keeps this aggregate's breadth anchored rather
    than excused — the gate does not care which vocabulary refuses the
    value, only that some refusal does.
    """
    accepted: list[str] = []
    for spelling, value in CARRIED_SPELLINGS:
        try:
            carry(agent_model_id=value)
        except Exception:  # noqa: BLE001, S112 - the finding is the
            # *acceptance*: the gate does not care which vocabulary refuses
            # the value, only that some refusal does, and the per-spelling
            # faces below pin the classes the shipped refusals carry.
            continue
        accepted.append(spelling)
    return tuple(accepted)


def record_refusal(record: Mapping[str, Any]) -> tuple[str, ...]:
    """The row face: the no-value spelling a rendered node record carries.

    A node record, once rendered, is a mapping of column to value — the
    shape :meth:`discovery.Attempt.row` answers and the shape a hand or a
    vendor writer would hand a tree. This face judges that mapping as
    data: the column read back, the absent key told apart from every
    present one, and the finding named in the spelling the record itself
    carries. Empty means the record carries a value and the merge stands
    over it — this face never writes, never opens, and never asks a store
    to vouch for a record the gate can read for itself.
    """
    carried = record.get(NODE_RECORD_COLUMN, MISSING)
    if not no_model_value(carried):
        return ()
    return (_SPELLING_OF.get(carried, f"agent_model_id={carried!r}"),)


# ── The gate reads the node record the merge carries ─────────────────────────


class TestTheGateReadsTheNodeRecordTheMergeCarries:
    """The gate judges the column, the field and the row a merge ships, as
    data, without writing anything."""


    def test_the_gate_reads_the_migration_that_owns_the_column(self) -> None:
        # The gate reads the column's own owner — feature 100's revision,
        # loaded by path the way a runner loads it, never a restatement
        # typed into this file. A gate that re-typed the constraint it
        # judged could agree with itself and pass anything; this one fails
        # the moment the owner moves or changes.
        assert MIGRATION.REVISION == TRIO_REVISION
        assert NODE_RECORD_COLUMN in MIGRATION.COLUMNS
        assert NODE_RECORD_COLUMN in MIGRATION.NOT_NULL_COLUMNS
        assert MIGRATION.COLUMN_TYPES[NODE_RECORD_COLUMN] == ("TEXT", "TEXT")

    def test_the_column_is_declared_not_null_on_both_dialects(self) -> None:
        # The DDL face. On both dialects exactly one statement adds the
        # column, it carries NOT NULL, and no statement anywhere carries a
        # DEFAULT — 0115's own refusal, restated as the gate's: a default
        # would have to be true of every row that predates the column, and
        # "unknown" is not a model stratum but a fabricated one. A merge
        # that softened either half — the constraint dropped, a default
        # slipped in to ease the backfill — fails here, before any row.
        for dialect in ("other", "sqlite"):
            statements = MIGRATION.statements(dialect)
            adding = [
                statement
                for statement in statements
                if f"ADD COLUMN {NODE_RECORD_COLUMN} " in statement
            ]
            assert len(adding) == 1, (dialect, statements)
            assert "NOT NULL" in adding[0].upper()
            assert not any(
                "DEFAULT" in statement.upper() for statement in statements
            )

    def test_the_records_field_is_required_not_defaulted(self) -> None:
        # The record face, read as a signature. The model field has no
        # default and no factory: a defaulted field is how "carries no
        # value" becomes the merge's out-of-the-box configuration — a
        # caller omits the keyword and the record builds. The trio's other
        # two members make the pin non-vacuous, because their defaults are
        # legal and for stated reasons: the checkpoint's ``None`` is §9.1's
        # hosted-API fact, and the sampling's factory is the dice known at
        # authoring time. The model is the one member of the trio with no
        # honest default, and the field says so.
        fields = {field.name: field for field in dataclasses.fields(AttemptProvenance)}
        model = fields[NODE_RECORD_COLUMN]
        assert model.default is dataclasses.MISSING
        assert model.default_factory is dataclasses.MISSING
        assert fields["agent_ckpt_hash"].default is None
        assert fields["agent_sampling"].default_factory is not dataclasses.MISSING

    def test_the_row_the_merge_renders_carries_the_column(self) -> None:
        # The row face's subject exists: the write path renders its node
        # record as a mapping, and the mapping carries the column with the
        # value the provenance stated — one spelling of the value, one
        # place, so the row cannot disagree with the record that produced
        # it. The gate's judgement of that row is the judgement of the
        # shipped shape.
        row = gate_attempt(gate_provenance()).row(GATE_ARTIFACT_URI)
        assert row[NODE_RECORD_COLUMN] == GATE_TRIPLE
        assert record_refusal(row) == ()

    def test_the_gate_judges_the_record_without_opening_a_database(self) -> None:
        # A merge gate refuses the change before it ships; the subject here
        # is a record, and a record is data. The static check the ledger
        # and labeler gates apply to their evaluators, pinned for all of
        # this gate's: none touches anything that could open, drive or
        # settle a connection — a gate that had to run a write to judge it
        # would be an audit after the fact.
        for evaluator in (no_model_value, merge_refusal, record_refusal):
            tree = ast.parse(inspect.getsource(evaluator))
            database_names = [
                node.attr
                for node in ast.walk(tree)
                if isinstance(node, ast.Attribute)
                and node.attr
                in {
                    "connect",
                    "cursor",
                    "execute",
                    "executescript",
                    "commit",
                    "rollback",
                }
            ]
            assert database_names == []

    def test_the_read_the_merge_ships_refuses_the_rows_the_writer_cannot_produce(
        self,
    ) -> None:
        # The read-side belt, held as the merge's third face. The shipped
        # stratification read refuses exactly the two spellings the write
        # path cannot produce on a database the chain built — NULL and the
        # blank that TRIM catches — in the member's own words because "a
        # diversity figure that quietly shrank would flatter exactly the
        # model whose nodes went missing." A merge that weakened this
        # predicate (dropped the TRIM half, bucketed the NULLs) would let
        # valueless rows silently shrink the per-model figure, and fails
        # here before any campaign runs.
        assert f"n.{NODE_RECORD_COLUMN} IS NULL" in _UNMODELLED_SQL
        assert f"TRIM(n.{NODE_RECORD_COLUMN}) = ''" in _UNMODELLED_SQL

    def test_the_composition_registers_the_pin_store_under_one_name(
        self, test_database_url: str
    ) -> None:
        # The composed configuration's identity: the member registers the
        # column's stamping store under one name — restated as data here —
        # and the builder it registers resolves the deployment's own
        # DATABASE_URL at build time, so the composed application carries
        # the store the process is actually running in. The loader imports
        # member packages under scan aliases, so the registered builder is
        # structurally the exported function but never the same module
        # object a direct import yields — the member's own registration
        # suites state the rule: verify name and behaviour, never identity
        # across the two module worlds. The behavioural half here is the
        # plain-data field: the URL the built store writes to is the URL
        # the deployment named.
        components = {
            component.name: component.builder
            for component in registered_components()
        }
        builder = components[AGENT_MODEL_PINS_COMPONENT]
        assert builder.__name__ == build_agent_model_pins.__name__
        assert builder.__module__.endswith("providers")
        store = builder()
        assert store is not None
        assert store.database_url == test_database_url


# ── A merge whose node records carry a model stands ──────────────────────────


class TestAMergeWhoseNodeRecordsCarryAModelStands:
    """The shipped surfaces, exercised once over a deterministic record,
    carry a triple end to end — the merge stands by construction."""


    def test_the_provenance_record_carries_the_triple_into_the_row(self) -> None:
        # The stands case stated end-to-end: the deployment supplies the
        # triple, the record validates and carries it, and the row the
        # write path renders states it under the column's own name — the
        # one value, spelled once, from the caller's argument to the row
        # the tree would hold.
        provenance = gate_provenance()
        assert provenance.agent_model_id == GATE_TRIPLE
        row = gate_attempt(provenance).row(GATE_ARTIFACT_URI)
        assert row[NODE_RECORD_COLUMN] == GATE_TRIPLE

    def test_the_pin_seam_normalizes_a_carried_triple(self) -> None:
        # The pin face's stands case: feature 203's one parse of the stored
        # form reads the triple back into its three parts — the provider,
        # the model, the snapshot — and renders it to the column's own
        # spelling, which cross-checks the gate's restated value against
        # the member's own rendering: one string, one model, one stratum.
        pin = require_agent_model_id(GATE_TRIPLE)
        assert isinstance(pin, ModelPin)
        assert (pin.provider, pin.model, pin.version) == GATE_TRIPLE_PARTS
        assert pin.agent_model_id == GATE_TRIPLE

    def test_the_column_accepts_a_row_that_carries_a_model(self) -> None:
        # The belt's stands side, on a table the chain itself built: the
        # insert naming the column with a value lands, and the row reads
        # the value back untouched — the constraint refuses only the
        # absence, never the livelihood. A gate that could not say this
        # would be refusing the column, not the missing value.
        with closing(_chain_built_node_table()) as connection:
            connection.execute(
                f"INSERT INTO {MIGRATION.NODE_TABLE} "
                f"(id, {NODE_RECORD_COLUMN}, agent_sampling) "
                "VALUES ('n-modelled', ?, '{}')",
                (GATE_TRIPLE,),
            )
            stored = connection.execute(
                f"SELECT {NODE_RECORD_COLUMN} FROM {MIGRATION.NODE_TABLE} "
                "WHERE id = 'n-modelled'"
            ).fetchone()
        assert stored == (GATE_TRIPLE,)

    def test_the_store_backfills_the_one_state_the_column_could_not_cover(
        self, tmp_path: Path
    ) -> None:
        # The repair path, and the reason the refusal is honest rather
        # than dogmatic. A brought-forward table — the hand-edited shape
        # where a NULL can exist at all, because the chain's own column
        # refuses it — is diagnosed by the store (load answers None, the
        # absence, distinguished from a node that is not there), and
        # feature 203's persist writes the triple in as the backfill. The
        # second row still answers None: the honest absence is reported,
        # never bucketed, and it is the backfill's job — not the
        # stratification's — to say which model authored it.
        database = tmp_path / "brought-forward.db"
        with closing(sqlite3.connect(database)) as connection, connection:
            connection.execute(
                f"CREATE TABLE {MIGRATION.NODE_TABLE} ("
                "id TEXT PRIMARY KEY, agent_model_id TEXT, "
                "agent_ckpt_hash CHAR(64), agent_sampling TEXT)"
            )
            connection.execute(
                f"INSERT INTO {MIGRATION.NODE_TABLE} (id) VALUES (?)",
                (GATE_PARENT,),
            )
            connection.execute(
                f"INSERT INTO {MIGRATION.NODE_TABLE} (id) VALUES (?)",
                (GATE_OTHER_NODE,),
            )
        pins = AgentModelPins(f"sqlite:///{database}")
        assert pins.load(GATE_PARENT) is None
        answer = pins.persist(GATE_PARENT, GATE_TRIPLE)
        assert answer.recorded is True
        assert answer.agent_model_id == GATE_TRIPLE
        assert pins.load(GATE_PARENT) is not None
        assert pins.load(GATE_OTHER_NODE) is None


# ── A merge whose node record carries no value is refused ────────────────────


class TestAMergeWhoseNodeRecordCarriesNoValueIsRefused:
    """Every no-value spelling is refused by every surface the merge ships —
    and a surface that accepts one is the refusal, whatever else that merge
    does."""


    @pytest.mark.parametrize(("description", "value"), CARRIED_SPELLINGS)
    def test_every_no_value_spelling_is_refused_at_construction(
        self, description: str, value: Any
    ) -> None:
        # The record face, one spelling at a time. The refusal is the
        # member's own class and names the column and the constraint, so
        # the operator reads the finding off the exception — a record that
        # cannot be built is an attempt that cannot be logged, and the
        # tree never meets the row.
        with pytest.raises(AttemptLogError) as excinfo:
            gate_provenance(agent_model_id=value)
        message = str(excinfo.value)
        assert NODE_RECORD_COLUMN in message
        assert "NOT NULL" in message

    @pytest.mark.parametrize(("description", "value"), CARRIED_SPELLINGS)
    def test_the_pin_seam_refuses_every_spelling(
        self, description: str, value: Any
    ) -> None:
        # The pin face: feature 203's parse is strict in both directions,
        # and the valueless spellings are refused before any store is
        # consulted — in the member's own vocabulary, because a caller
        # that catches the feature's refusal gets the same answer however
        # the value was absent.
        with pytest.raises(RollingAliasError):
            require_agent_model_id(value)

    def test_the_store_refuses_the_valueless_pin_before_it_opens(
        self, tmp_path: Path
    ) -> None:
        # The ordering pin: the store validates the pin before it resolves
        # its path, so a valueless pin is refused without the database so
        # much as existing. The refusal is a fact about the record, not a
        # transaction that rolled back — nothing was opened, nothing was
        # read, and a deployment pointed at a database that does not exist
        # still hears about the value, not the file.
        database = tmp_path / "absent.db"
        pins = AgentModelPins(f"sqlite:///{database}")
        with pytest.raises(RollingAliasError):
            pins.persist(GATE_PARENT, None)
        assert not database.exists()

    def test_every_shipped_record_surface_refuses_every_spelling(self) -> None:
        # The gate's own happy path, stated as the gate states it: both
        # record surfaces the merge ships — the provenance record's
        # construction, and the pin seam's parse of the stored form —
        # refuse every no-value spelling. Empty findings on both, so the
        # merge stands.
        assert merge_refusal(gate_provenance) == ()
        assert (
            merge_refusal(
                lambda **kwargs: require_agent_model_id(
                    kwargs[NODE_RECORD_COLUMN]
                )
            )
            == ()
        )

    def test_a_surface_that_accepts_a_spelling_is_the_refusal(self) -> None:
        # The load-bearing regression case. The witness accepts every
        # no-value spelling — its constructor defaults the field and never
        # refuses — and the gate names each spelling it accepted,
        # deterministically, in the order the law's own words suggest them.
        # A future edit that weakened a shipped surface (the field given a
        # default, the validation demoted to a warning) turns the test
        # above non-empty right here, at merge time, before any row exists.
        assert merge_refusal(lambda **kwargs: UnpinnedRecord(**kwargs)) == tuple(
            description for description, _ in CARRIED_SPELLINGS
        )

    def test_the_row_face_names_the_absent_key(self) -> None:
        # The row face's discrimination. The witness's default record
        # omits the column entirely — the absence wearing a writer's shape
        # — and the face names the absent key; the same record asked to
        # carry the empty string renders the key with the value that names
        # no model, and the face names that spelling instead. The shipped
        # row above answers empty on both counts: the finding is named
        # where it exists and only where it exists.
        absent, _ = NO_VALUE_SPELLINGS[0]
        empty, _ = NO_VALUE_SPELLINGS[2]
        assert record_refusal(UnpinnedRecord().row()) == (absent,)
        assert record_refusal(UnpinnedRecord(agent_model_id="").row()) == (empty,)
        assert record_refusal(
            gate_attempt(gate_provenance()).row(GATE_ARTIFACT_URI)
        ) == ()

    def test_the_column_refuses_the_row_the_chain_built(self) -> None:
        # The belt behind the belt: on a table the assembled chain builds,
        # the insert that names no model value is refused by the column
        # itself, in the engine's own words naming the column — the
        # constraint the DDL declares, doing what it says ahead of the
        # write. Even a caller that bypassed every record surface meets
        # the sentence here.
        with (
            closing(_chain_built_node_table()) as connection,
            pytest.raises(sqlite3.IntegrityError) as excinfo,
        ):
            connection.execute(
                f"INSERT INTO {MIGRATION.NODE_TABLE} "
                "(id, agent_sampling) VALUES ('n-unmodelled', '{}')"
            )
        assert NODE_RECORD_COLUMN in str(excinfo.value)


# ── The finding is exactly the absent value and nothing else ─────────────────


class TestTheFindingIsExactlyTheAbsentValueAndNothingElse:
    """The gate refuses exactly the sentence's finding: a record that
    carries no value for the named column — never a value that names a
    target, a sibling's honest NULL, or a record that joins."""


    def test_a_value_that_names_a_model_is_not_the_finding(self) -> None:
        # The stands side of the evaluator, stated at the evaluator: a
        # triple, a padded triple, a bare word — each strips non-empty and
        # is a value the record carries. Whether a value names a model
        # truthfully is a question about the value's content, and this
        # sentence's question is about its absence.
        assert not no_model_value(GATE_TRIPLE)
        assert not no_model_value(f"  {GATE_TRIPLE} ")
        assert not no_model_value("momentum")

    def test_a_rolling_alias_is_a_value_and_not_this_gates_finding(self) -> None:
        # The scope boundary, pinned from both sides. ``'deepseek-flash'``
        # is §14.1's own example of the alias that re-routes — and it is a
        # value this gate does not refuse: the record seam accepts it as
        # non-empty text, because the record's law is presence. The pin
        # seam refuses it, under feature 203's own sentence and in its own
        # vocabulary. The two sentences divide the labour exactly: 358
        # refuses the absence, 203 refuses the alias, and a gate that
        # conflated them would refuse merges for a finding that is not
        # this one's.
        assert not no_model_value("deepseek-flash")
        assert gate_provenance(agent_model_id="deepseek-flash").agent_model_id == (
            "deepseek-flash"
        )
        with pytest.raises(RollingAliasError):
            require_agent_model_id("deepseek-flash")

    def test_the_trios_one_nullable_column_is_a_recorded_fact(self) -> None:
        # The named column is the finding, and its siblings are not. The
        # trio's one nullable member records hosted-API weights with its
        # NULL — §9.1's own annotation, "non-null for self-hosted weights"
        # — so a record with no checkpoint hash is complete, and the model
        # column beside it still carries the value that makes the row
        # stratifiable. A gate that refused the sibling's NULL would be
        # refusing hosted-API deployments the spec explicitly permits.
        record = gate_provenance()
        assert record.agent_ckpt_hash is None
        assert not no_model_value(record.agent_model_id)

    def test_the_history_that_joins_is_not_the_record_that_carries(self) -> None:
        # The other quiet absence, and why the gate judges node records
        # rather than grepping for the column name: the signal agent's
        # proposal history deliberately carries no copy of the column — a
        # copy "would be a second spelling of it that can drift from the
        # stratum the paired comparison actually groups by", so "a reader
        # that wants it joins". That design is legal, this gate does not
        # refuse it, and the pin is stated so a future gate cannot quietly
        # widen the sentence to cover it.
        assert NODE_RECORD_COLUMN not in _PROPOSAL_SCHEMA
